"""
rugo — a fast, dependency-free file engine for Parquet, CSV, and JSONL.

Reading **and** writing, with zero heavy dependencies: no PyArrow, no NumPy on
any path. Compiled as C++/Cython extensions. Readers emit Draken vectors; the
writers consume Draken Morsels — the bundled ``draken`` columnar substrate.

    from rugo import parquet
    with parquet.read_parquet("data.parquet", columns=["id", "name"]) as r:
        for morsel in r:
            ...
"""

try:
    import pyarrow  # noqa: F401  # pyarrow has a load-order bug: it must be imported before rugo's native extensions
except ImportError:
    pass

# opteryx_core, rugo and libskene each bundle draken to the same path, so the
# last install wins. Verify the winner is the draken this build was compiled
# against before rugo_native resolves its draken_* symbols against it.
# Generated by build_common at build time.
from rugo._draken_abi import check_draken_abi

check_draken_abi()

import draken  # load draken_native.so before rugo_native.so resolves its symbols

from rugo.__version__ import __version__

__all__ = ["__version__"]
