"""
rugo — a fast, dependency-free file engine for Parquet, CSV, and JSONL.

Reading **and** writing, with zero heavy dependencies: no PyArrow, no NumPy on
any path. Compiled as C++/Cython extensions. Readers emit Draken vectors; the
writers consume Draken Morsels — the bundled ``draken`` columnar substrate.

    from rugo import parquet
    with parquet.read_parquet("data.parquet", columns=["id", "name"]) as r:
        for morsel in r:
            ...
"""

try:
    import pyarrow  # noqa: F401  # pyarrow has a load-order bug: it must be imported before rugo's native extensions
except ImportError:
    pass

# opteryx_core, rugo and libskene each bundle draken to the same path, so the
# last install wins. Verify the winner is the draken this build was compiled
# against before rugo_native resolves its draken_* symbols against it.
# Generated by build_common at build time.
from rugo._draken_abi import check_draken_abi

check_draken_abi()

import draken  # load draken_native.so before rugo_native.so resolves its symbols

from rugo.__version__ import __version__

# rugo ships in two distributions, and `__version__` above is always the
# STANDALONE rugo source version — it does not change when rugo is bundled
# inside opteryx_core, which stamps its own version into the parquet footers it
# writes. So `__version__` alone cannot be reconciled with a file's created_by.
# These two can: they are generated at build time from the exact string that is
# compiled into the writer. See build_common.write_rugo_build_identity.
from rugo._build_identity import RUGO_DISTRIBUTION as __distribution__
from rugo._build_identity import RUGO_WRITER_ID as __writer_id__

__all__ = ["__version__", "__writer_id__", "__distribution__"]
