# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# See the License at http://www.apache.org/licenses/LICENSE-2.0
# Distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.

"""
Reader for trace files.

Parses JSONLines trace files generated by the tracing system and provides
structured access to events and computed metrics.
"""

import json
from pathlib import Path
from typing import Any
from typing import Dict
from typing import Iterator
from typing import List
from typing import Optional


class TraceReader:
    """
    Reads and parses IO trace files (.jsonl format).

    Example:
        >>> reader = TraceReader("/tmp/io_trace.jsonl")
        >>> for event in reader.events():
        ...     print(event["type"], event["file_id"])
        >>> metadata = reader.metadata()
        >>> print(metadata["query"])
    """

    def __init__(self, filepath: str, strict: bool = False):
        """
        Initialize trace reader.

        Args:
            filepath: Path to .jsonl trace file
            strict: If True, raise on parse errors. If False, skip bad lines.
        """
        self.filepath = Path(filepath)
        self.strict = strict
        self._metadata: Optional[Dict[str, Any]] = None
        self._events: Optional[List[Dict[str, Any]]] = None

    def events(self) -> Iterator[Dict[str, Any]]:
        """
        Iterate over all events in the trace file.

        Yields:
            Event dictionaries (one per line of JSONLines file)

        Raises:
            ValueError: If strict=True and a line cannot be parsed
        """
        if not self.filepath.exists():
            raise FileNotFoundError(f"Trace file not found: {self.filepath}")

        with open(self.filepath, "r", encoding="utf-8") as f:
            for line_no, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue

                try:
                    event = json.loads(line)
                    yield event
                except json.JSONDecodeError as e:
                    if self.strict:
                        raise ValueError(f"Parse error at line {line_no}: {e}")
                    else:
                        # Log warning but continue (in production, use logging module)
                        print(f"Warning: Skipping invalid line {line_no}: {e}")

    def metadata(self) -> Dict[str, Any]:
        """
        Get session metadata (from trace_session_start event).

        Returns:
            Metadata dictionary
        """
        if self._metadata is not None:
            return self._metadata

        # Find the trace_session_start event
        for event in self.events():
            if event["type"] == "trace_session_start":
                self._metadata = event
                return self._metadata

        # If no metadata event, return empty dict
        self._metadata = {}
        return self._metadata

    def file_timelines(self) -> Dict[str, Dict[str, Any]]:
        """
        Organize events by file, creating a timeline for each file.

        Returns:
            Dict mapping file_id → file timeline dict with keys:
            - discovered: timestamp when file was discovered
            - download_start: timestamp when download began
            - download_complete: timestamp when download ended
            - decode_start: timestamp when decoding began
            - decode_complete: timestamp when decoding ended
            - size_bytes: file size (if available)
            - rows_decoded: number of rows (if available)
            - batches: number of batches (if available)
        """
        timelines = {}

        for event in self.events():
            file_id = event.get("file_id")
            if not file_id:
                continue

            if file_id not in timelines:
                timelines[file_id] = {}

            timeline = timelines[file_id]
            event_type = event.get("type")

            if event_type == "file_discovered":
                timeline["discovered"] = event.get("timestamp")
                timeline["size_bytes"] = event.get("size_bytes")
            elif event_type == "download_start":
                timeline["download_start"] = event.get("timestamp")
            elif event_type == "download_complete":
                timeline["download_complete"] = event.get("timestamp")
                timeline["bytes_received"] = event.get("bytes_received") or 0
            elif event_type == "decode_start":
                timeline["decode_start"] = event.get("timestamp")
            elif event_type == "decode_complete":
                timeline["decode_complete"] = event.get("timestamp")
                timeline["rows_decoded"] = event.get("rows_decoded") or 0
                timeline["batches"] = event.get("batches") or 0

        return timelines

    def statistics(self) -> Dict[str, Any]:
        """
        Compute statistics from the trace.

        Returns:
            Dictionary with computed metrics:
            - total_files: number of files processed
            - total_bytes: total bytes downloaded
            - total_rows: total rows decoded
            - download_phase_duration_ms: time from first download_start to last download_complete
            - decode_phase_duration_ms: time from first decode_start to last decode_complete
            - query_duration_ms: total time from first to last event
            - max_concurrent_downloads: peak files downloading simultaneously
            - avg_download_time_ms: average per-file download time
            - avg_decode_time_ms: average per-file decode time
        """
        timelines = self.file_timelines()

        if not timelines:
            return {
                "total_files": 0,
                "total_bytes": 0,
                "total_rows": 0,
                "download_phase_duration_ms": 0,
                "decode_phase_duration_ms": 0,
                "query_duration_ms": 0,
                "max_concurrent_downloads": 0,
                "avg_download_time_ms": 0,
                "avg_decode_time_ms": 0,
            }

        total_files = len(timelines)
        total_bytes = sum(t.get("bytes_received", 0) for t in timelines.values())
        total_rows = sum(t.get("rows_decoded", 0) for t in timelines.values())

        # Find time boundaries
        all_starts = [
            t.get("download_start") for t in timelines.values() if t.get("download_start")
        ]
        all_ends = [
            t.get("decode_complete") for t in timelines.values() if t.get("decode_complete")
        ]

        query_start = min(all_starts) if all_starts else None
        query_end = max(all_ends) if all_ends else None

        query_duration_ms = (query_end - query_start) * 1000 if query_start and query_end else 0

        # Download phase duration
        download_starts = [
            t.get("download_start") for t in timelines.values() if t.get("download_start")
        ]
        download_ends = [
            t.get("download_complete") for t in timelines.values() if t.get("download_complete")
        ]
        download_phase_duration_ms = (
            (max(download_ends) - min(download_starts)) * 1000
            if download_starts and download_ends
            else 0
        )

        # Decode phase duration
        decode_starts = [t.get("decode_start") for t in timelines.values() if t.get("decode_start")]
        decode_ends = [
            t.get("decode_complete") for t in timelines.values() if t.get("decode_complete")
        ]
        decode_phase_duration_ms = (
            (max(decode_ends) - min(decode_starts)) * 1000 if decode_starts and decode_ends else 0
        )

        # Average times
        download_times = [
            (t.get("download_complete", 0) - t.get("download_start", 0)) * 1000
            for t in timelines.values()
            if t.get("download_start") and t.get("download_complete")
        ]
        avg_download_time_ms = sum(download_times) / len(download_times) if download_times else 0

        decode_times = [
            (t.get("decode_complete", 0) - t.get("decode_start", 0)) * 1000
            for t in timelines.values()
            if t.get("decode_start") and t.get("decode_complete")
        ]
        avg_decode_time_ms = sum(decode_times) / len(decode_times) if decode_times else 0

        # Max concurrent downloads (simplified - count overlapping)
        max_concurrent = self._compute_max_concurrency(
            timelines, "download_start", "download_complete"
        )

        return {
            "total_files": total_files,
            "total_bytes": total_bytes,
            "total_rows": total_rows,
            "download_phase_duration_ms": download_phase_duration_ms,
            "decode_phase_duration_ms": decode_phase_duration_ms,
            "query_duration_ms": query_duration_ms,
            "max_concurrent_downloads": max_concurrent,
            "avg_download_time_ms": avg_download_time_ms,
            "avg_decode_time_ms": avg_decode_time_ms,
        }

    def _compute_max_concurrency(
        self, timelines: Dict[str, Dict[str, Any]], start_key: str, end_key: str
    ) -> int:
        """Compute max number of overlapping operations."""
        events = []

        for timeline in timelines.values():
            if start_key in timeline and end_key in timeline:
                events.append((timeline[start_key], 1))  # Start
                events.append((timeline[end_key], -1))  # End

        if not events:
            return 0

        events.sort()
        max_concurrent = 0
        current = 0

        for _, delta in events:
            current += delta
            max_concurrent = max(max_concurrent, current)

        return max_concurrent
