#!/usr/bin/env python3
"""
Signals benchmark runner for Opteryx.

Runs the query suite under tests/performance/signals/queries/ against the
synthetic "signals" (security-scanner findings) dataset generated by
dev/generate_signals_data.py. Each query lives in its own .sql file (one
query per file), so complex, customer-shaped queries can be added
independently instead of accumulating in one big embedded list.

There is no DuckDB baseline for this dataset -- it's synthetic and only
exists in this repo -- so this suite reports Opteryx timings only.

For each query:
  - substitutes the {DATASET} placeholder with the quoted dataset path,
  - opens a fresh Opteryx session per iteration,
  - executes via session.execute_to_morsels() and drains the iterator,
  - times wall-clock,
  - enforces a per-query timeout,
  - writes per-iteration rows to results/<sha>-<ts>.csv.
"""

from __future__ import annotations

import argparse
import gc
import os
import re
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
_REPO_ROOT = HERE.parents[2]
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_REPO_ROOT / "tests" / "performance"))

from _common import (  # noqa: E402
    open_results_csv,
    print_banner,
    print_error_row,
    print_header,
    print_row,
    print_skip_row,
)

import opteryx  # noqa: E402

DEFAULT_DATASET = "scratch/signals_synthetic"


def _run_one(sql: str, timeout_s: float) -> tuple[str, float, int, str]:
    gc.collect()
    t0 = time.monotonic_ns()
    deadline = time.monotonic() + timeout_s
    rows = 0
    session = None
    try:
        session = opteryx.session()
        for morsel in session.execute_to_morsels(sql):
            if morsel is not None and hasattr(morsel, "num_rows"):
                rows += morsel.num_rows
            if time.monotonic() > deadline:
                elapsed_ms = (time.monotonic_ns() - t0) / 1e6
                return ("timeout", elapsed_ms, rows, f"exceeded {timeout_s:.0f}s")
        return ("ok", (time.monotonic_ns() - t0) / 1e6, rows, "")
    except Exception as e:
        msg = f"{type(e).__name__}: {e}"
        return ("error", (time.monotonic_ns() - t0) / 1e6, rows, msg[:500])
    finally:
        if session is not None:
            try:
                session.close()
            except Exception:
                pass


def _collect(queries_dir: Path) -> list[Path]:
    return sorted(queries_dir.glob("*.sql"), key=lambda p: p.name)


def main() -> int:
    parser = argparse.ArgumentParser(description="Signals benchmark runner for Opteryx")
    parser.add_argument(
        "--dataset",
        type=str,
        default=DEFAULT_DATASET,
        help=f"dataset path substituted for {{DATASET}} (default: {DEFAULT_DATASET})",
    )
    parser.add_argument("--queries-dir", type=Path, default=HERE / "queries")
    parser.add_argument("--results-dir", type=Path, default=HERE / "results")
    parser.add_argument(
        "--timeout",
        type=float,
        default=300.0,
        help="per-query wall-clock timeout in seconds (default: 300)",
    )
    parser.add_argument(
        "--filter",
        type=str,
        default=None,
        help="run only queries whose stem matches this regex",
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=2,
        help="iterations per query (default: 2 -- cold + warm)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.dataset):
        print(f"[!] dataset not found: {args.dataset}")
        print(
            "    generate it with: python -m dev.generate_signals_data "
            f"--rows 10_000_000 --out {args.dataset}"
        )
        return 1

    queries = _collect(args.queries_dir)
    if args.filter:
        flt = re.compile(args.filter)
        queries = [q for q in queries if flt.match(q.stem)]
    if not queries:
        print(f"[!] no queries matched in {args.queries_dir}")
        return 1

    print_banner(
        title="Signals benchmark",
        opteryx_version=opteryx.__version__,
        metadata=[
            ("Dataset", args.dataset),
            ("Queries", str(len(queries))),
            ("Iterations", f"{args.iterations} per query (1=cold, 2=warm)"),
            ("Timeout", f"{args.timeout:.0f}s/query"),
        ],
    )

    print_header("Query", args.iterations, has_baseline=False)

    csv_writer, csv_path, csv_handle = open_results_csv(
        str(args.results_dir),
        fieldnames=["query", "run", "status", "elapsed_ms", "row_count", "error"],
    )

    counts = {"ok": 0, "timeout": 0, "error": 0}
    suite_start = time.monotonic()

    try:
        for path in queries:
            stem = path.stem
            raw_sql = path.read_text()
            sql = raw_sql.replace("{DATASET}", f"'{args.dataset}'")

            run_times: list[float] = []
            had_failure = False
            for run_ix in range(1, args.iterations + 1):
                status, elapsed_ms, rows, msg = _run_one(sql, args.timeout)
                counts[status] += 1
                csv_writer.writerow(
                    {
                        "query": stem,
                        "run": run_ix,
                        "status": status,
                        "elapsed_ms": f"{elapsed_ms:.3f}",
                        "row_count": rows,
                        "error": msg,
                    }
                )
                csv_handle.flush()
                if status == "ok":
                    run_times.append(elapsed_ms)
                else:
                    if status == "timeout":
                        print_skip_row(stem, f"timeout: {msg}")
                    else:
                        print_error_row(stem, msg)
                    had_failure = True
                    break
            if had_failure or not run_times:
                continue
            print_row(stem, run_times, args.iterations, None)
    finally:
        csv_handle.close()

    suite_elapsed = time.monotonic() - suite_start
    print("─" * 100)
    print()
    print(
        f"\033[38;2;26;185;67m{counts['ok']} passed\033[0m, "
        f"\033[38;2;255;121;198m{counts['error']} failed\033[0m, "
        f"\033[38;2;255;165;0m{counts['timeout']} timeout\033[0m   "
        f"({suite_elapsed:.1f}s)"
    )
    print(f"  results: {os.path.relpath(csv_path, _REPO_ROOT)}")
    return 1 if counts["error"] else 0


if __name__ == "__main__":
    sys.exit(main())
