"""GROUP BY over a dictionary-encoded key, aggregating through the codes.

When a single GROUP BY key arrives dictionary-shaped and every aggregate is
COUNT(*), COUNT, SUM, AVG or numeric MIN/MAX, GroupBySink's pass C resolves each
row's group from its dictionary CODE (native_group_sinks.hpp, the dict path's
`row_kinds_only` branch) instead of filling per-row hash/group arrays.

Each test checks the answer against plain-Python ground truth AND that the code
pass actually ran (the `dict_codepass` telemetry counter) — a test that silently
exercised the generic path would prove nothing about this one. The same query is
re-run with OPTERYX_GB_CODEPASS=0 (read per query) as a second, independent oracle.

Data is generated by SQL formulas over generate_series and written with rugo's
writer (dictionary encoding on by default), several files so several morsels and
workers contribute. NULL keys and NULL operands are included.
"""
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

import pytest

import opteryx
import rugo.parquet as rp
from opteryx.connectors import DiskConnector
from opteryx.operators._operators import get_groupby_telemetry
from opteryx.operators._operators import reset_groupby_telemetry

FILES = 3
ROWS = 120_000

# Key: 37 distinct strings, NULL every 17th row. v: signed int, NULL every 5th row.
# f: float, NULL every 13th row. Formulas are mirrored exactly by _row() below.
_SQL = """SELECT
 'k' || CAST(CASE WHEN g % 17 = 0 THEN NULL ELSE (g * 69069) % 37 END AS VARCHAR) AS k,
 CASE WHEN g % 5 = 0 THEN NULL ELSE (g * 637) % 1000003 - 500000 END AS v,
 CASE WHEN g % 13 = 0 THEN NULL ELSE CAST((g * 1103515245) % 99991 AS FLOAT64) / 7.0 END AS f
 FROM generate_series({lo}, {hi}) AS g"""


def _row(g):
    k = None if g % 17 == 0 else f"k{(g * 69069) % 37}"
    v = None if g % 5 == 0 else (g * 637) % 1000003 - 500000
    f = None if g % 13 == 0 else float((g * 1103515245) % 99991) / 7.0
    return k, v, f


_WS = [0]


def _workspace(tmp, sql_template, files, rows):
    _WS[0] += 1
    ws = f"ws_codepass_{_WS[0]}"
    data_dir = os.path.join(tmp, ws, "t")
    os.makedirs(data_dir)
    for i in range(files):
        lo = i * rows + 1
        morsels = opteryx.session().execute_to_morsels(sql_template.format(lo=lo, hi=lo + rows - 1))
        with open(os.path.join(data_dir, f"part_{i}.parquet"), "wb") as fh:
            rp.write_parquet_stream(morsels, fh.write)
    opteryx.register_workspace(ws, DiskConnector)
    return ws


def _query(sql, codepass=True):
    """Rows of `sql` keyed by the first column, and the code-pass morsel count."""
    previous = os.environ.get("OPTERYX_GB_CODEPASS")
    os.environ["OPTERYX_GB_CODEPASS"] = "1" if codepass else "0"
    try:
        reset_groupby_telemetry()
        out = {}
        for m in opteryx.session().execute_to_morsels(sql):
            for i in range(m.num_rows):
                row = m[i]
                out[row[0]] = row[1:]
        return out, get_groupby_telemetry()["dict_codepass"]
    finally:
        if previous is None:
            del os.environ["OPTERYX_GB_CODEPASS"]
        else:
            os.environ["OPTERYX_GB_CODEPASS"] = previous


def _close(a, b):
    if a is None or b is None:
        return a is b
    if isinstance(a, float) or isinstance(b, float):
        return abs(a - b) <= 1e-9 * max(1.0, abs(a), abs(b))
    return a == b


def _assert_rows(got, want):
    assert set(got) == set(want), (sorted(map(str, got)), sorted(map(str, want)))
    for key, expected in want.items():
        actual = got[key]
        assert len(actual) == len(expected)
        for a, e in zip(actual, expected):
            assert _close(a, e), (key, actual, expected)


@pytest.fixture(scope="module")
def dataset():
    cwd = os.getcwd()
    with tempfile.TemporaryDirectory() as tmp:
        os.chdir(tmp)
        try:
            yield _workspace(tmp, _SQL, FILES, ROWS)
        finally:
            os.chdir(cwd)


def _ground_truth():
    groups = {}
    for g in range(1, FILES * ROWS + 1):
        k, v, f = _row(g)
        groups.setdefault(k, []).append((v, f))
    return groups


def test_codepass_all_row_kinds(dataset):
    sql = (
        f"SELECT k, COUNT(*), COUNT(v), SUM(v), MIN(v), MAX(v), AVG(v), "
        f"SUM(f), MIN(f), MAX(f), AVG(f) FROM {dataset}.t GROUP BY k"
    )
    want = {}
    for k, rows in _ground_truth().items():
        vs = [v for v, _ in rows if v is not None]
        fs = [f for _, f in rows if f is not None]
        want[k] = (
            len(rows),
            len(vs),
            sum(vs) if vs else None,
            min(vs) if vs else None,
            max(vs) if vs else None,
            sum(vs) / len(vs) if vs else None,
            sum(fs) if fs else None,
            min(fs) if fs else None,
            max(fs) if fs else None,
            sum(fs) / len(fs) if fs else None,
        )
    got, fired = _query(sql)
    assert fired > 0, "the dictionary code pass never ran — the test proves nothing"
    _assert_rows(got, want)
    # Independent oracle: the generic pass C over the same morsels.
    generic, fired_off = _query(sql, codepass=False)
    assert fired_off == 0
    _assert_rows(got, {k: v for k, v in generic.items()})


def test_codepass_filtered_and_having(dataset):
    sql = (
        f"SELECT k, SUM(v), COUNT(*) FROM {dataset}.t WHERE v > 0 "
        f"GROUP BY k HAVING COUNT(*) > 100"
    )
    want = {}
    for k, rows in _ground_truth().items():
        vs = [v for v, _ in rows if v is not None and v > 0]
        if len(vs) > 100:
            want[k] = (sum(vs), len(vs))
    got, fired = _query(sql)
    assert fired > 0
    _assert_rows(got, want)


def test_codepass_sum_overflow_fails_loud():
    """SUM's INT64 overflow trap holds on the code pass — never a wrapped answer."""
    sql_template = """SELECT CONCAT('k', CAST(g % 2 AS VARCHAR)) AS k,
     CAST(4611686018427387904 AS INT64) AS v FROM generate_series({lo}, {hi}) AS g"""
    cwd = os.getcwd()
    with tempfile.TemporaryDirectory() as tmp:
        os.chdir(tmp)
        try:
            ws = _workspace(tmp, sql_template, 1, 1000)
            with pytest.raises(Exception, match="SUM overflow"):
                _query(f"SELECT k, SUM(v) FROM {ws}.t GROUP BY k")
        finally:
            os.chdir(cwd)


if __name__ == "__main__":  # pragma: no cover
    pytest.main([__file__, "-v"])
