[package]
name = "compute"
version = "0.1.0"
authors = ["@joocer"]
edition = "2021"

[lib]
name = "compute"
crate-type = ["cdylib"]

# Link statically against libgcc/libstdc++ to avoid GLIBC_2.18 symbols
[profile.release]
strip = true
lto = true

[dependencies]
pythonize = "0.27"
serde = "1.0.171"

[dependencies.pyo3]
version = "0.27"
features = ["extension-module"]

[dependencies.sqlparser]
version = "0.61.0"
default-features = false
features = ["serde"]