#!/usr/bin/env python3
"""
Analyze function cost data and generate insights.

Usage:
    python analyze_function_costs.py function_costs.json

Generates:
- Cost statistics by category
- Fastest/slowest functions
- Cost trends and outliers
- Recommendations for optimization
"""

import json
from collections import defaultdict
from pathlib import Path
from typing import Any
from typing import Dict
from typing import List

import numpy as np


class CostAnalyzer:
    """Analyze function cost data."""

    def __init__(self, costs_file: Path):
        """Load cost data from JSON file.

        Args:
            costs_file: Path to JSON file generated by estimate_function_costs.py
        """
        with open(costs_file) as f:
            self.data = json.load(f)

        self.functions = self.data.get("functions", {})

    def extract_costs(self) -> Dict[str, float]:
        """Extract cost values for all successful kernels.

        Returns:
            Dictionary mapping "function:kernel" to cost in μs/million
        """
        costs = {}

        for func_name, kernels in self.functions.items():
            for kernel in kernels:
                if kernel.get("success", False):
                    key = f"{func_name}:{kernel['kernel_id']}"
                    costs[key] = kernel["cost_us_per_million"]

        return costs

    def get_function_categories(self) -> Dict[str, List[str]]:
        """Group functions by category from the catalog.

        Returns:
            Dictionary mapping category to list of function names
        """
        # This would ideally read from the actual catalog
        # For now, we'll group by name prefix/patterns
        categories = defaultdict(list)

        for func_name in self.functions:
            if func_name.startswith(("SHA", "MD5", "BASE", "HEX")):
                categories["hash_encoding"].append(func_name)
            elif func_name.startswith(("YEAR", "MONTH", "DAY", "HOUR", "DATE", "TIME")):
                categories["temporal"].append(func_name)
            elif func_name.startswith(("UPPER", "LOWER", "SUBSTR", "CONCAT", "LENGTH", "TRIM")):
                categories["string"].append(func_name)
            elif func_name in ("SUM", "AVG", "COUNT", "MIN", "MAX", "ARRAY_AGG"):
                categories["aggregate"].append(func_name)
            elif func_name in ("ABS", "ROUND", "FLOOR", "CEIL", "SQRT", "POWER"):
                categories["arithmetic"].append(func_name)
            else:
                categories["other"].append(func_name)

        return dict(categories)

    def analyze_cost_distribution(self) -> Dict[str, Any]:
        """Analyze the distribution of costs.

        Returns:
            Dictionary with statistical summaries
        """
        costs = list(self.extract_costs().values())

        if not costs:
            return {"error": "No successful cost measurements"}

        return {
            "count": len(costs),
            "min": float(np.min(costs)),
            "max": float(np.max(costs)),
            "mean": float(np.mean(costs)),
            "median": float(np.median(costs)),
            "std_dev": float(np.std(costs)),
            "p25": float(np.percentile(costs, 25)),
            "p75": float(np.percentile(costs, 75)),
            "p95": float(np.percentile(costs, 95)),
        }

    def get_fastest_functions(self, n: int = 10) -> List[tuple]:
        """Get the fastest (lowest cost) functions.

        Args:
            n: Number of functions to return

        Returns:
            List of (name, cost) tuples sorted by cost
        """
        costs = self.extract_costs()
        sorted_costs = sorted(costs.items(), key=lambda x: x[1])
        return sorted_costs[:n]

    def get_slowest_functions(self, n: int = 10) -> List[tuple]:
        """Get the slowest (highest cost) functions.

        Args:
            n: Number of functions to return

        Returns:
            List of (name, cost) tuples sorted by cost descending
        """
        costs = self.extract_costs()
        sorted_costs = sorted(costs.items(), key=lambda x: x[1], reverse=True)
        return sorted_costs[:n]

    def analyze_by_engine(self) -> Dict[str, Dict[str, Any]]:
        """Analyze costs grouped by execution engine.

        Returns:
            Dictionary with statistics per engine
        """
        by_engine = defaultdict(list)

        for func_name, kernels in self.functions.items():
            for kernel in kernels:
                if kernel.get("success", False):
                    engine = kernel.get("engine", "unknown")
                    cost = kernel["cost_us_per_million"]
                    by_engine[engine].append(cost)

        results = {}
        for engine, costs in by_engine.items():
            results[engine] = {
                "count": len(costs),
                "mean": float(np.mean(costs)),
                "median": float(np.median(costs)),
                "min": float(np.min(costs)),
                "max": float(np.max(costs)),
                "std_dev": float(np.std(costs)),
            }

        return results

    def identify_outliers(self, threshold_std: float = 2.0) -> List[tuple]:
        """Identify functions with unusual (outlier) costs.

        Args:
            threshold_std: Number of standard deviations for outlier threshold

        Returns:
            List of (name, cost, z_score) tuples
        """
        costs = self.extract_costs()
        cost_values = list(costs.values())

        if len(cost_values) < 2:
            return []

        mean = np.mean(cost_values)
        std = np.std(cost_values)

        if std == 0:
            return []

        outliers = []
        for name, cost in costs.items():
            z_score = abs((cost - mean) / std)
            if z_score > threshold_std:
                outliers.append((name, cost, z_score))

        return sorted(outliers, key=lambda x: x[2], reverse=True)

    def generate_report(self) -> str:
        """Generate a comprehensive analysis report.

        Returns:
            Formatted report string
        """
        lines = []
        lines.append("=" * 80)
        lines.append("FUNCTION COST ANALYSIS REPORT")
        lines.append("=" * 80 + "\n")

        # Summary stats
        stats = self.analyze_cost_distribution()
        if "error" not in stats:
            lines.append("COST DISTRIBUTION")
            lines.append("-" * 80)
            lines.append(f"Total kernels measured: {stats['count']}")
            lines.append(f"Range: {stats['min']:.2f} - {stats['max']:.2f} μs/million")
            lines.append(f"Mean: {stats['mean']:.2f} μs/million")
            lines.append(f"Median: {stats['median']:.2f} μs/million")
            lines.append(f"Std Dev: {stats['std_dev']:.2f}")
            lines.append(f"P25: {stats['p25']:.2f} μs/million")
            lines.append(f"P75: {stats['p75']:.2f} μs/million")
            lines.append(f"P95: {stats['p95']:.2f} μs/million\n")

        # By engine
        lines.append("COSTS BY EXECUTION ENGINE")
        lines.append("-" * 80)
        by_engine = self.analyze_by_engine()
        for engine in sorted(by_engine.keys()):
            stats = by_engine[engine]
            lines.append(
                f"{engine:<15} count={stats['count']:<3} "
                f"mean={stats['mean']:>10.2f} median={stats['median']:>10.2f} "
                f"(range: {stats['min']:.2f}-{stats['max']:.2f})"
            )
        lines.append()

        # Fastest functions
        lines.append("TOP 10 FASTEST FUNCTIONS")
        lines.append("-" * 80)
        for name, cost in self.get_fastest_functions(10):
            lines.append(f"{name:<40} {cost:>12.2f} μs/million")
        lines.append()

        # Slowest functions
        lines.append("TOP 10 SLOWEST FUNCTIONS")
        lines.append("-" * 80)
        for name, cost in self.get_slowest_functions(10):
            lines.append(f"{name:<40} {cost:>12.2f} μs/million")
        lines.append()

        # Outliers
        outliers = self.identify_outliers()
        if outliers:
            lines.append("POTENTIAL OPTIMIZATION CANDIDATES (Statistical Outliers)")
            lines.append("-" * 80)
            for name, cost, z_score in outliers[:10]:
                lines.append(
                    f"{name:<40} {cost:>12.2f} μs/million (z-score: {z_score:.2f})"
                )
            lines.append()

        lines.append("=" * 80)

        return "\n".join(lines)


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Analyze function cost data"
    )
    parser.add_argument(
        "costs_file",
        type=Path,
        help="JSON file with cost estimates",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Save report to file (default: print to stdout)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output as JSON instead of formatted text",
    )

    args = parser.parse_args()

    if not args.costs_file.exists():
        print(f"Error: File not found: {args.costs_file}")
        return 1

    analyzer = CostAnalyzer(args.costs_file)

    if args.json:
        # Export as JSON
        export = {
            "distribution": analyzer.analyze_cost_distribution(),
            "by_engine": analyzer.analyze_by_engine(),
            "fastest": [
                {"name": n, "cost": c} for n, c in analyzer.get_fastest_functions(10)
            ],
            "slowest": [
                {"name": n, "cost": c} for n, c in analyzer.get_slowest_functions(10)
            ],
            "outliers": [
                {"name": n, "cost": c, "z_score": z}
                for n, c, z in analyzer.identify_outliers()
            ],
        }
        output = json.dumps(export, indent=2)
    else:
        output = analyzer.generate_report()

    if args.output:
        args.output.write_text(output)
        print(f"Report written to: {args.output}")
    else:
        print(output)

    return 0


if __name__ == "__main__":
    main()
