#!/usr/bin/env python3
"""Delete Cython-generated C/C++ sources so the next build re-runs Cython.

`make clean` removes compiled `.so` files but NOT the `.c`/`.cpp` that Cython
emits next to each `.pyx`. cythonize caches those by source content, so a change
to `compiler_directives` (or any setup.py compile flag) does NOT bust them — the
stale generated file is recompiled and the new directive never lands. This bit us
when adding the free-threading (`freethreading_compatible`) slot.

Detection is by the Cython banner — `/* Generated by Cython ... */` on the first
line — NOT by ".pyx sibling". That guarantees we only ever delete files Cython
produced: vendored or hand-written C/C++ (which lack the banner) is never touched.
"""

import os
import sys

# Cython writes this as the very first line of every generated module.
MARKER = b"Generated by Cython"

# Extensions Cython can emit (.c for C modules, .cpp for cpp=True modules).
SUFFIXES = (".c", ".cpp", ".cc")

# Directories that never contain our Cython output; skip for speed/safety.
SKIP_DIRS = {".git", "build", "dist", "target", ".mypy_cache", ".pytest_cache", "__pycache__"}


def is_cython_generated(path: str) -> bool:
    # The banner is on line 1; read a small chunk rather than the whole file.
    with open(path, "rb") as handle:
        return MARKER in handle.readline()


def main() -> int:
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    removed = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if not name.endswith(SUFFIXES):
                continue
            path = os.path.join(dirpath, name)
            if is_cython_generated(path):
                os.remove(path)
                print(f"removed {path}")
                removed += 1
    print(f"clean_cython_generated: removed {removed} Cython-generated file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
