#!/usr/bin/env python3
"""
Convert a parquet dataset tree to its skene mirror.

Walks a source tree of `<table>/<file>.parquet` datasets (the testdata TPC-H
layout) and writes `<table>/<table>-NNNN.skene` into the destination —
16 ROW GROUPS per file at 262144 rows per row group (architect decision
2026-08-08), which is ~4.2M rows per file.

WHY THIS IS NOT ONE FILE PER SOURCE ROW GROUP any more: it used to be, because
one .skene file WAS one row group. The ClickBench mirror was then 396 objects
against parquet's 99 for the same data, and per-file fixed cost (~0.1ms locally
for open+mmap and the footer read, tens of milliseconds per GET remotely) is
paid before a byte of data is read.

WHY THE SOURCE ROW GROUPS ARE RE-CHUNKED rather than passed through: the target
is 262144 rows per row group, and source row groups are not that size. TPC-H's
are 41350 and 65536; passing them through would produce 16-row-group files whose
row groups were a quarter of the intended size, which changes the scan's work
item size — the thing the row group count exists to control.

Written read-first by default: read_acceleration on, compression OFF. Read
performance is king for LTS writes (architect ruling 2026-08-07), and
per-section zstd is the dominant read tax on local storage — measured on TPC-H
lineitem, one DECIMAL column decodes in 2.0ms raw vs 38.8ms compressed (19x),
all 16 columns 127ms vs 441ms — for ~2.7x the disk. Network-bound remote
storage inverts that trade.

Usage:
    python dev/parquet_to_skene.py <src> <dst> [codec] [zstd-level]

    codec is `none` (default), `lz4`, or `zstd`; a zstd level may follow `zstd`
    and defaults to 9 (writer.h WriteOptions::for_storage). Mirrors for a
    codec bake-off are generated by varying this argument:

    python dev/parquet_to_skene.py testdata/tpch_10 testdata/tpch_10_skene
    python dev/parquet_to_skene.py testdata/tpch_10 testdata/tpch_10_skene_lz4 lz4
    python dev/parquet_to_skene.py testdata/tpch_10 testdata/tpch_10_skene_z9 zstd 9

The destination must not already hold .skene files. Output file names depend on
the packing, so writing over an older mirror would leave BOTH generations in the
directory and the dataset would be a mixture — refused rather than merged.

Dev tooling only — never imported by production code (repo rules §5).
"""

from __future__ import annotations

import os
import sys
import time

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, _REPO_ROOT)

import skene  # noqa: E402
from draken.morsels.morsel import Morsel  # noqa: E402
from rugo.parquet import read_parquet  # noqa: E402

# Architect decision, 2026-08-08. 262144 rows is where parquet landed too — the
# balance between amortising remote IO and the cost of processing one unit — and
# 16 was chosen against measurements of file count against scan parallelism.
#
# Neither is a format constant: the format says nothing about how many row groups
# a file holds or how big they are. They are this tool's policy.
ROWS_PER_ROW_GROUP = 262_144
ROW_GROUPS_PER_FILE = 16


class _Packer:
    """Buffers decoded morsels and emits fixed-size row groups into skene files.

    The buffer holds at most one row group's worth plus one source morsel, so
    peak memory is bounded by the row group size rather than by the file size —
    which is the whole reason the writer streams.
    """

    def __init__(self, out_dir: str, stem: str, codec: str, zstd_level: int):
        self._out_dir = out_dir
        self._stem = stem
        self._codec = codec
        self._zstd_level = zstd_level

        self._pending: list = []
        self._pending_rows = 0
        self._writer = None
        self._row_groups_in_file = 0

        self.files = 0
        self.rows = 0
        self.nbytes = 0

    def add(self, morsel) -> None:
        if morsel.num_rows == 0:
            return
        self._pending.append(morsel)
        self._pending_rows += morsel.num_rows
        while self._pending_rows >= ROWS_PER_ROW_GROUP:
            merged = (
                self._pending[0] if len(self._pending) == 1 else Morsel.combine(self._pending)
            )
            self._emit(merged.slice(0, ROWS_PER_ROW_GROUP))
            remainder = merged.num_rows - ROWS_PER_ROW_GROUP
            if remainder > 0:
                self._pending = [merged.slice(ROWS_PER_ROW_GROUP, remainder)]
            else:
                self._pending = []
            self._pending_rows = remainder

    def close(self) -> None:
        """Flush the tail. The final row group is SHORT, and so is the final
        file — a dataset does not divide evenly and pretending otherwise would
        mean either padding it or dropping the remainder."""
        if self._pending_rows > 0:
            merged = (
                self._pending[0] if len(self._pending) == 1 else Morsel.combine(self._pending)
            )
            self._emit(merged)
            self._pending = []
            self._pending_rows = 0
        self._close_file()

    def _emit(self, row_group) -> None:
        if self._writer is None:
            self._writer = skene.SkeneWriter(
                read_acceleration=True, codec=self._codec, zstd_level=self._zstd_level
            )
            self._row_groups_in_file = 0
        self._writer.add_row_group(row_group)
        self._row_groups_in_file += 1
        self.rows += row_group.num_rows
        if self._row_groups_in_file >= ROW_GROUPS_PER_FILE:
            self._close_file()

    def _close_file(self) -> None:
        if self._writer is None:
            return
        path = os.path.join(self._out_dir, f"{self._stem}-{self.files:04d}.skene")
        # write_to() completes the file and writes it with no intermediate copy —
        # a packed file of a wide schema is hundreds of megabytes and finish()
        # would double the peak to hand back bytes nobody keeps.
        self.nbytes += self._writer.write_to(path)
        self.files += 1
        self._writer = None
        self._row_groups_in_file = 0


def convert_dir(
    parquet_paths: list, out_dir: str, stem: str, codec: str = "none", zstd_level: int = 0
) -> tuple[int, int, int]:
    """Every parquet file in ONE directory -> packed .skene files.

    Packing is per DIRECTORY, not per file: row groups are re-chunked to a fixed
    size, so a row group can span two source files and a source file no longer
    corresponds to any particular output file.
    """
    packer = _Packer(out_dir, stem, codec, zstd_level)
    for parquet_path in parquet_paths:
        with read_parquet(parquet_path) as reader:
            for morsel in reader:
                packer.add(morsel)
    packer.close()
    if packer.files == 0:
        raise RuntimeError(
            f"{out_dir}: no row groups read — refusing to write an empty table"
        )
    return packer.files, packer.rows, packer.nbytes


def main() -> int:
    # Third argument selects the CODEC, fourth its level. This argument used to
    # be a bare zstd level, so a numeric one is rejected by name rather than
    # reinterpreted — an old command line silently producing a different mirror
    # than it used to is exactly the kind of quiet drift a benchmark cannot
    # survive.
    if len(sys.argv) not in (3, 4, 5):
        print(__doc__)
        return 1
    src_root, dst_root = sys.argv[1], sys.argv[2]
    codec = sys.argv[3] if len(sys.argv) >= 4 else "none"
    if codec.lstrip("-").isdigit():
        print(
            f"ERROR: the third argument is now the CODEC name, not a zstd level "
            f"(got {codec!r}) — use: {sys.argv[0]} <src> <dst> zstd {codec}"
        )
        return 1
    if codec not in ("none", "lz4", "zstd"):
        print(f"ERROR: unknown codec {codec!r} — expected 'none', 'lz4' or 'zstd'")
        return 1

    # The level is meaningful only for zstd, and skene's writer REJECTS a level
    # set alongside another codec rather than ignoring it, so this mirrors that
    # rule instead of passing a contradiction down.
    if codec == "zstd":
        # 9 is WriteOptions::for_storage()'s level: zstd decodes at a rate that
        # does not depend on the level, so a low level gives up ratio and buys
        # nothing back on read.
        zstd_level = int(sys.argv[4]) if len(sys.argv) == 5 else 9
    else:
        if len(sys.argv) == 5:
            print(f"ERROR: a zstd level was given but the codec is {codec!r}")
            return 1
        zstd_level = 0

    if not os.path.isdir(src_root):
        print(f"ERROR: source dataset tree not found: {src_root}")
        return 1

    # Output names are a function of the packing, so an older mirror's files do
    # not get overwritten — they get JOINED, and the dataset becomes a mixture of
    # two layouts. Refuse rather than merge.
    if os.path.isdir(dst_root):
        stale = [
            os.path.join(dirpath, name)
            for dirpath, _dirnames, filenames in os.walk(dst_root)
            for name in filenames
            if name.endswith(".skene")
        ]
        if stale:
            print(
                f"ERROR: {dst_root} already holds {len(stale)} .skene file(s). This "
                f"converter packs 16 row groups per file, so its output names do not "
                f"line up with an older mirror's and writing here would leave BOTH "
                f"generations in place.\n       Remove it first:  rm -rf {dst_root}"
            )
            return 1

    described = "zstd-%d" % zstd_level if codec == "zstd" else codec
    print(
        f"codec={described}, read_acceleration=True, "
        f"{ROW_GROUPS_PER_FILE} row groups/file at {ROWS_PER_ROW_GROUP:,} rows"
    )

    started = time.monotonic()
    total_files = total_rows = total_bytes = src_bytes = 0
    total_row_groups = 0
    for dirpath, _dirnames, filenames in sorted(os.walk(src_root)):
        parquet_files = sorted(f for f in filenames if f.lower().endswith(".parquet"))
        if not parquet_files:
            continue
        rel = os.path.relpath(dirpath, src_root)
        out_dir = os.path.join(dst_root, rel) if rel != "." else dst_root
        os.makedirs(out_dir, exist_ok=True)

        # One stem per directory, because packing is per directory. Named after
        # the destination directory so the files say which table they are.
        stem = os.path.basename(os.path.normpath(out_dir)) or "part"
        paths = [os.path.join(dirpath, name) for name in parquet_files]
        src_size = sum(os.path.getsize(p) for p in paths)

        files, rows, nbytes = convert_dir(paths, out_dir, stem, codec, zstd_level)
        src_bytes += src_size
        total_files += files
        total_rows += rows
        total_bytes += nbytes
        row_groups = -(-rows // ROWS_PER_ROW_GROUP)
        total_row_groups += row_groups
        print(
            f"  {rel:<20} {len(parquet_files):>4} parquet -> {files:>4} skene file(s), "
            f"{row_groups:>5} row group(s), {rows:>12,} rows, "
            f"{src_size / 1e6:8.1f}MB -> {nbytes / 1e6:8.1f}MB "
            f"(avg {nbytes / files / 1e6:6.1f}MB/file)"
        )

    if total_files == 0:
        print(f"ERROR: no .parquet files found under {src_root}")
        return 1

    elapsed = time.monotonic() - started
    print(
        f"\nConverted {total_rows:,} rows into {total_files} skene files "
        f"({total_row_groups} row groups) in {elapsed:.1f}s "
        f"({src_bytes / 1e6:.1f}MB parquet -> {total_bytes / 1e6:.1f}MB skene, "
        f"{total_bytes / src_bytes:.2f}x)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
