# Auto-generated consolidated module placeholder
# DO NOT EDIT - generated by setup.py

include "count.pyx"
include "count_distinct.pyx"
include "count_star.pyx"
include "sum_float64.pyx"
include "sum_int64.pyx"
include "min_max_fixed.pyx"
include "min_max_var.pyx"
include "avg_float64.pyx"
include "avg_int64.pyx"
include "any_value_fixed.pyx"
include "any_value_var.pyx"
