# Auto-generated consolidated module
# DO NOT EDIT - generated by setup.py

include "group_by_draken_kernels/00_common.pyx"
include "group_by_draken_kernels/10_count_star_int64.pyx"
include "group_by_draken_kernels/20_count_distinct_int64.pyx"
include "group_by_draken_kernels/30_avg_int64_float64.pyx"
include "group_by_draken_kernels/90_factory.pyx"
