"""
WP-5: bounded retries + per-request timeouts for remote range reads.

HttpClient.get_many() now retries individual range requests that fail with a
transient cause (5xx/429 or a connection/timeout/partial-transfer CURL error),
with exponential backoff + jitter, up to OPTERYX_HTTP_MAX_RETRIES (default 2).
4xx (except 429) is a hard error and is NOT retried. Exhausted retries raise a
clear error naming the cause, url, and range.

These tests drive the real C++ client against dev/throttle_server.py with
injected faults. Retry config is read once per process into statics, so the
suite runs with the default (2 retries) — tests are designed around that.
"""

import os
import subprocess
import sys
import time

import pytest

sys.path.insert(1, os.path.join(sys.path[0], "../../../.."))

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../../dev/bench_data")
DATA_DIR = os.path.abspath(DATA_DIR)
SERVER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../../dev/throttle_server.py")
SERVER = os.path.abspath(SERVER)
FNAME = "remote_io_bench.parquet"


def _ensure_data():
    """The bench dataset is generated by dev/bench_remote_io.py; create it if absent."""
    path = os.path.join(DATA_DIR, FNAME)
    if not os.path.isfile(path):
        import pyarrow as pa
        import pyarrow.parquet as pq

        os.makedirs(DATA_DIR, exist_ok=True)
        t = pa.table({"id": pa.array(list(range(100000)), type=pa.int64())})
        pq.write_table(t, path)
    return path


def _server(error_rate=0.0, seed=1):
    proc = subprocess.Popen(
        [sys.executable, SERVER, "--root", DATA_DIR, "--port", "0",
         "--error-rate", str(error_rate), "--seed", str(seed)],
        stdout=subprocess.PIPE, text=True,
    )
    port = int(proc.stdout.readline().strip().split("port=")[1])
    return proc, port


def _url(port):
    return f"http://127.0.0.1:{port}/{FNAME}"


def test_no_fault_succeeds():
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(0.0)
    try:
        out = HttpClient().get_many([(_url(port), {"Range": "bytes=0-4095"})])
        assert len(out[0]) == 4096
    finally:
        proc.kill(); proc.wait()


def test_persistent_5xx_raises_exhausted():
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(1.0)  # every request 503
    try:
        with pytest.raises(RuntimeError) as ei:
            HttpClient().get_many([(_url(port), {"Range": "bytes=0-1023"})])
        assert "exhaust" in str(ei.value).lower()
    finally:
        proc.kill(); proc.wait()


def test_4xx_not_retried_and_immediate():
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(0.0)
    try:
        t0 = time.monotonic()
        with pytest.raises(RuntimeError) as ei:
            HttpClient().get_many([(f"http://127.0.0.1:{port}/missing.parquet", {"Range": "bytes=0-1023"})])
        elapsed = time.monotonic() - t0
        assert "404" in str(ei.value)
        # No retry/backoff on a 4xx — should return effectively immediately.
        assert elapsed < 1.0, f"4xx took {elapsed:.2f}s, suggesting it was retried"
    finally:
        proc.kill(); proc.wait()


def test_transient_faults_recover():
    """With a 30% transient fault rate and the default 2 retries (3 attempts),
    P(recover) per request is 1 - 0.3**3 ≈ 0.973, so essentially every read
    should succeed. Assert a strong majority across trials (loose bound to stay
    robust to the seeded fault sequence)."""
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(0.3, seed=11)
    try:
        c = HttpClient()
        recovered = 0
        trials = 20
        for i in range(trials):
            try:
                out = c.get_many([(_url(port), {"Range": f"bytes={i*64}-{i*64+1023}"})])
                recovered += len(out[0]) == 1024
            except RuntimeError:
                pass
        # Without retries this would be ~70%; with retries expect ≥90%.
        assert recovered >= int(trials * 0.85), f"only {recovered}/{trials} recovered"
    finally:
        proc.kill(); proc.wait()


# Runs in a child so OPTERYX_HTTP_* (read once per process into statics) apply.
# Server: 8 Mbps = 1 MB/s PER CONNECTION, so a 256 KiB range takes ~256 ms.
# Client assumes 16 Mbps = 2 MB/s, so ONE range's own budget is ~131 ms - too
# short for any range, alone or batched. A 12-range batch over the 3-connection
# host cap takes ~4 x 256 ms = ~1 s; its whole-batch budget is 12 x 131 ms = ~1.6 s.
_BATCH_BUDGET_CHILD = r"""
import sys
from opteryx.compiled.http_client import HttpClient
url, which = sys.argv[1], sys.argv[2]
KIB256 = 256 * 1024
if which == "single":
    reqs = [(url, {"Range": f"bytes=0-{KIB256 - 1}"})]
else:
    reqs = [(url, {"Range": f"bytes={i * KIB256}-{(i + 1) * KIB256 - 1}"}) for i in range(12)]
try:
    out = HttpClient().get_many(reqs)
    assert all(len(b) == KIB256 for b in out)
    print("OK")
except RuntimeError as e:
    print("ERR " + str(e))
"""


def _run_budget_child(port, which):
    env = dict(os.environ, OPTERYX_HTTP_TIMEOUT_FLOOR_MS="50", OPTERYX_HTTP_MIN_BW_MBPS="16")
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../.."))
    res = subprocess.run(
        [sys.executable, "-c", _BATCH_BUDGET_CHILD, _url(port), which],
        env=env, cwd=root, capture_output=True, text=True, timeout=60,
    )
    return res.stdout.strip() + res.stderr.strip()


def test_get_many_budget_covers_the_whole_batch():
    """The time budget is sized from the batch's TOTAL bytes, because every
    range in a get_many batch shares the same connections. The single-range
    control proves the throttle really bites at these settings (a range cannot
    finish inside its own budget), and pins the exhausted-retries diagnostics."""
    _ensure_data()
    proc = subprocess.Popen(
        [sys.executable, SERVER, "--root", DATA_DIR, "--port", "0", "--bandwidth-mbps", "8"],
        stdout=subprocess.PIPE, text=True,
    )
    port = int(proc.stdout.readline().strip().split("port=")[1])
    try:
        control = _run_budget_child(port, "single")
        assert control.startswith("ERR "), control
        assert "Timeout" in control, control
        assert "timeout=131ms" in control, control
        assert "batch=1 ranges/262144B" in control, control
        assert "received=" in control and "/262144B" in control, control
        assert "elapsed=" in control, control

        assert _run_budget_child(port, "batch") == "OK"
    finally:
        proc.kill(); proc.wait()


if __name__ == "__main__":
    test_no_fault_succeeds(); print("no-fault: OK")
    test_persistent_5xx_raises_exhausted(); print("persistent 5xx exhausted: OK")
    test_4xx_not_retried_and_immediate(); print("4xx immediate, no retry: OK")
    test_transient_faults_recover(); print("transient recover: OK")
    test_get_many_budget_covers_the_whole_batch(); print("batch budget: OK")
    print("all WP-5 tests passed")
