"""
WP-5: bounded retries + per-request timeouts for remote range reads.

HttpClient.get_many() now retries individual range requests that fail with a
transient cause (5xx/429 or a connection/timeout/partial-transfer CURL error),
with exponential backoff + jitter, up to OPTERYX_HTTP_MAX_RETRIES (default 2).
4xx (except 429) is a hard error and is NOT retried. Exhausted retries raise a
clear error naming the cause, url, and range.

These tests drive the real C++ client against dev/throttle_server.py with
injected faults. Retry config is read once per process into statics, so the
suite runs with the default (2 retries) — tests are designed around that.
"""

import os
import subprocess
import sys
import time

import pytest

sys.path.insert(1, os.path.join(sys.path[0], "../../../.."))

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../../dev/bench_data")
DATA_DIR = os.path.abspath(DATA_DIR)
SERVER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../../dev/throttle_server.py")
SERVER = os.path.abspath(SERVER)
FNAME = "remote_io_bench.parquet"


def _ensure_data():
    """The bench dataset is generated by dev/bench_remote_io.py; create it if absent."""
    path = os.path.join(DATA_DIR, FNAME)
    if not os.path.isfile(path):
        import pyarrow as pa
        import pyarrow.parquet as pq

        os.makedirs(DATA_DIR, exist_ok=True)
        t = pa.table({"id": pa.array(list(range(100000)), type=pa.int64())})
        pq.write_table(t, path)
    return path


def _server(error_rate=0.0, seed=1):
    proc = subprocess.Popen(
        [sys.executable, SERVER, "--root", DATA_DIR, "--port", "0",
         "--error-rate", str(error_rate), "--seed", str(seed)],
        stdout=subprocess.PIPE, text=True,
    )
    port = int(proc.stdout.readline().strip().split("port=")[1])
    return proc, port


def _url(port):
    return f"http://127.0.0.1:{port}/{FNAME}"


def test_no_fault_succeeds():
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(0.0)
    try:
        out = HttpClient().get_many([(_url(port), {"Range": "bytes=0-4095"})])
        assert len(out[0]) == 4096
    finally:
        proc.kill(); proc.wait()


def test_persistent_5xx_raises_exhausted():
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(1.0)  # every request 503
    try:
        with pytest.raises(RuntimeError) as ei:
            HttpClient().get_many([(_url(port), {"Range": "bytes=0-1023"})])
        assert "exhaust" in str(ei.value).lower()
    finally:
        proc.kill(); proc.wait()


def test_4xx_not_retried_and_immediate():
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(0.0)
    try:
        t0 = time.monotonic()
        with pytest.raises(RuntimeError) as ei:
            HttpClient().get_many([(f"http://127.0.0.1:{port}/missing.parquet", {"Range": "bytes=0-1023"})])
        elapsed = time.monotonic() - t0
        assert "404" in str(ei.value)
        # No retry/backoff on a 4xx — should return effectively immediately.
        assert elapsed < 1.0, f"4xx took {elapsed:.2f}s, suggesting it was retried"
    finally:
        proc.kill(); proc.wait()


def test_transient_faults_recover():
    """With a 30% transient fault rate and the default 2 retries (3 attempts),
    P(recover) per request is 1 - 0.3**3 ≈ 0.973, so essentially every read
    should succeed. Assert a strong majority across trials (loose bound to stay
    robust to the seeded fault sequence)."""
    from opteryx.compiled.http_client import HttpClient

    _ensure_data()
    proc, port = _server(0.3, seed=11)
    try:
        c = HttpClient()
        recovered = 0
        trials = 20
        for i in range(trials):
            try:
                out = c.get_many([(_url(port), {"Range": f"bytes={i*64}-{i*64+1023}"})])
                recovered += len(out[0]) == 1024
            except RuntimeError:
                pass
        # Without retries this would be ~70%; with retries expect ≥90%.
        assert recovered >= int(trials * 0.85), f"only {recovered}/{trials} recovered"
    finally:
        proc.kill(); proc.wait()


if __name__ == "__main__":
    test_no_fault_succeeds(); print("no-fault: OK")
    test_persistent_5xx_raises_exhausted(); print("persistent 5xx exhausted: OK")
    test_4xx_not_retried_and_immediate(); print("4xx immediate, no retry: OK")
    test_transient_faults_recover(); print("transient recover: OK")
    print("all WP-5 tests passed")
