# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# See the License at http://www.apache.org/licenses/LICENSE-2.0
# Distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.

"""
Reader for trace files.

Parses JSONLines trace files generated by the tracing system and provides
structured access to events and computed metrics.
"""

import json
from collections import defaultdict
from collections import deque
from pathlib import Path
from typing import Any
from typing import Dict
from typing import Iterator
from typing import List
from typing import Optional


class TraceReader:
    """
    Reads and parses IO trace files (.jsonl format).

    Example:
        >>> reader = TraceReader("/tmp/io_trace.jsonl")
        >>> for event in reader.events():
        ...     print(event["type"], event["file_id"])
        >>> metadata = reader.metadata()
        >>> print(metadata["query"])
    """

    def __init__(self, filepath: str, strict: bool = False):
        """
        Initialize trace reader.

        Args:
            filepath: Path to .jsonl trace file
            strict: If True, raise on parse errors. If False, skip bad lines.
        """
        self.filepath = Path(filepath)
        self.strict = strict
        self._metadata: Optional[Dict[str, Any]] = None
        self._events: Optional[List[Dict[str, Any]]] = None

    def _load_events(self) -> List[Dict[str, Any]]:
        """Load and cache trace events from disk."""
        if self._events is not None:
            return self._events

        if not self.filepath.exists():
            raise FileNotFoundError(f"Trace file not found: {self.filepath}")

        loaded: List[Dict[str, Any]] = []
        with open(self.filepath, "r", encoding="utf-8") as f:
            for line_no, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue

                try:
                    event = json.loads(line)
                    loaded.append(event)
                except json.JSONDecodeError as e:
                    if self.strict:
                        raise ValueError(f"Parse error at line {line_no}: {e}")
                    else:
                        # Log warning but continue (in production, use logging module)
                        print(f"Warning: Skipping invalid line {line_no}: {e}")

        self._events = loaded
        return self._events

    def events(self) -> Iterator[Dict[str, Any]]:
        """
        Iterate over all events in the trace file.

        Yields:
            Event dictionaries (one per line of JSONLines file)

        Raises:
            ValueError: If strict=True and a line cannot be parsed
        """
        yield from self._load_events()

    def metadata(self) -> Dict[str, Any]:
        """
        Get session metadata (from trace_session_start event).

        Returns:
            Metadata dictionary
        """
        if self._metadata is not None:
            return self._metadata

        # Find the trace_session_start event
        for event in self._load_events():
            if event["type"] == "trace_session_start":
                self._metadata = event
                return self._metadata

        # If no metadata event, return empty dict
        self._metadata = {}
        return self._metadata

    def file_timelines(self) -> Dict[str, Dict[str, Any]]:
        """
        Organize events by file, creating a timeline for each file.

        Returns:
            Dict mapping file_id → file timeline dict with keys:
            - discovered: timestamp when file was discovered
            - download_start: timestamp when download began
            - download_complete: timestamp when download ended
            - decode_start: timestamp when decoding began
            - decode_complete: timestamp when decoding ended
            - size_bytes: file size (if available)
            - rows_decoded: number of rows (if available)
            - batches: number of batches (if available)
        """
        timelines = {}

        for event in self._load_events():
            file_id = event.get("file_id")
            if not file_id:
                continue

            if file_id not in timelines:
                timelines[file_id] = {}

            timeline = timelines[file_id]
            event_type = event.get("type")

            if event_type == "file_discovered":
                timeline["discovered"] = event.get("timestamp")
                timeline["size_bytes"] = event.get("size_bytes")
            elif event_type == "download_start":
                timeline["download_start"] = event.get("timestamp")
            elif event_type == "download_complete":
                timeline["download_complete"] = event.get("timestamp")
                timeline["bytes_received"] = event.get("bytes_received") or 0
            elif event_type == "buffer_start":
                if "buffer_start" not in timeline:
                    timeline["buffer_start"] = event.get("timestamp")
            elif event_type == "buffer_complete":
                timeline["buffer_complete"] = event.get("timestamp")
            elif event_type == "decode_start":
                timeline["decode_start"] = event.get("timestamp")
            elif event_type == "decode_complete":
                timeline["decode_complete"] = event.get("timestamp")
                timeline["rows_decoded"] = event.get("rows_decoded") or 0
                timeline["batches"] = event.get("batches") or 0

        return timelines

    @staticmethod
    def _normalized_component(event: Dict[str, Any], phase: str) -> str:
        """Normalize component names into stable operation groupings."""
        component = event.get("component")
        if not component:
            return "file"
        if phase == "download" and component == "columns":
            # Downloaded bytes for a row group are emitted as `columns`.
            # Align with decode `rowgroup` events so both phases share one lane.
            return "rowgroup"
        return str(component)

    @staticmethod
    def _operation_key(event: Dict[str, Any], phase: str) -> tuple:
        """Build a key for matching start/complete events."""
        file_id = event.get("file_id")
        component = TraceReader._normalized_component(event, phase)
        rg_idx = event.get("rg_idx")

        if component == "rowgroup":
            return file_id, component, rg_idx
        if component == "column":
            return file_id, component, rg_idx, event.get("column")
        return file_id, component, None

    @staticmethod
    def _operation_label(
        file_id: str, component: str, rg_idx: Any = None, column: Any = None
    ) -> str:
        """Human-readable label for one operation row."""
        base = Path(file_id).name if file_id else "unknown"
        if component == "file":
            return base
        if component == "footer":
            return f"{base} [footer]"
        if component == "rowgroup":
            return f"{base} [rg {rg_idx}]"
        if component == "column":
            return f"{base} [rg {rg_idx} col {column}]"
        return f"{base} [{component}]"

    @staticmethod
    def _row_start_timestamp(row: Dict[str, Any]) -> float:
        """Earliest timestamp available for sorting rows on the timeline."""
        candidates = [
            row.get("download_start"),
            row.get("download_complete"),
            row.get("decode_start"),
            row.get("decode_complete"),
        ]
        valid = [t for t in candidates if isinstance(t, (int, float))]
        return min(valid) if valid else float("inf")

    def operation_timelines(self) -> List[Dict[str, Any]]:
        """
        Build operation-level timelines from raw events.

        Unlike ``file_timelines()``, this preserves footer and row-group activity
        so the chart can represent the real scheduler behavior.
        """
        operations: List[Dict[str, Any]] = []
        operations_by_key: Dict[tuple, List[int]] = defaultdict(list)
        pending_download: Dict[tuple, deque] = defaultdict(deque)
        pending_decode: Dict[tuple, deque] = defaultdict(deque)
        op_counters: Dict[tuple, int] = defaultdict(int)

        def new_operation(key: tuple) -> int:
            if len(key) == 4:
                file_id, component, rg_idx, column = key
            else:
                file_id, component, rg_idx = key
                column = None

            sequence = op_counters[key]
            op_counters[key] += 1
            op_id = f"{file_id}|{component}|{rg_idx}|{column}|{sequence}"
            row = {
                "id": op_id,
                "file_id": file_id,
                "component": component,
                "rg_idx": rg_idx,
                "column": column,
                "label": self._operation_label(file_id, component, rg_idx, column),
                "download_start": None,
                "download_complete": None,
                "buffer_start": None,
                "buffer_complete": None,
                "decode_start": None,
                "decode_complete": None,
                "bytes_received": 0,
                "rows_decoded": 0,
            }
            operations.append(row)
            idx = len(operations) - 1
            operations_by_key[key].append(idx)
            return idx

        for event in self._load_events():
            event_type = event.get("type")
            if event_type not in {
                "download_start",
                "download_complete",
                "buffer_start",
                "buffer_complete",
                "decode_start",
                "decode_complete",
            }:
                continue

            if event_type.startswith("download_"):
                phase = "download"
            elif event_type.startswith("buffer_"):
                phase = "buffer"
            else:
                phase = "decode"
            key = self._operation_key(event, phase)
            if key[0] is None:
                continue
            if phase == "decode" and self._normalized_component(event, phase) == "column":
                # Column decode emits "complete" events only and can produce
                # thousands of instant points that drown the waterfall view.
                continue

            if event_type == "download_start":
                idx = new_operation(key)
                operations[idx]["download_start"] = event.get("timestamp")
                pending_download[key].append(idx)
                continue

            if event_type == "download_complete":
                idx = pending_download[key].popleft() if pending_download[key] else None
                if idx is None:
                    for candidate in reversed(operations_by_key.get(key, [])):
                        if operations[candidate]["download_complete"] is None:
                            idx = candidate
                            break
                if idx is None:
                    idx = new_operation(key)
                operations[idx]["download_complete"] = event.get("timestamp")
                operations[idx]["bytes_received"] += int(event.get("bytes_received") or 0)
                continue

            if event_type == "decode_start":
                idx = None
                for candidate in reversed(operations_by_key.get(key, [])):
                    row = operations[candidate]
                    if row["decode_start"] is None and (
                        row["download_start"] is not None or row["download_complete"] is not None
                    ):
                        idx = candidate
                        break
                if idx is None:
                    idx = new_operation(key)
                operations[idx]["decode_start"] = event.get("timestamp")
                pending_decode[key].append(idx)
                continue

            if event_type == "buffer_start":
                idx = None
                for candidate in reversed(operations_by_key.get(key, [])):
                    row = operations[candidate]
                    if row["buffer_start"] is None and row["download_complete"] is not None:
                        idx = candidate
                        break
                if idx is None:
                    idx = new_operation(key)
                operations[idx]["buffer_start"] = event.get("timestamp")
                continue

            if event_type == "buffer_complete":
                idx = None
                for candidate in reversed(operations_by_key.get(key, [])):
                    row = operations[candidate]
                    if row["buffer_start"] is not None and row["buffer_complete"] is None:
                        idx = candidate
                        break
                if idx is None:
                    idx = new_operation(key)
                operations[idx]["buffer_complete"] = event.get("timestamp")
                continue

            # decode_complete
            idx = pending_decode[key].popleft() if pending_decode[key] else None
            if idx is None:
                for candidate in reversed(operations_by_key.get(key, [])):
                    row = operations[candidate]
                    if row["decode_start"] is not None and row["decode_complete"] is None:
                        idx = candidate
                        break
            if idx is None:
                idx = new_operation(key)
            operations[idx]["decode_complete"] = event.get("timestamp")
            operations[idx]["rows_decoded"] = int(event.get("rows_decoded") or 0)

        operations.sort(key=lambda row: (self._row_start_timestamp(row), row.get("label", "")))
        return operations

    def exec_timelines(self) -> tuple:
        """Return (ops, t0, total_duration) for the operator execution waterfall.

        ops is a list of dicts with keys:
            operator_name, operator_id, wall_start, wall_end, rows_out, duration_ns

        wall_start / wall_end are relative to t0 (trace_session_start timestamp).
        total_duration is the wall time of the full session in seconds.
        Returns ([], None, None) when no operator_execute events are present.
        """
        events = self._load_events()
        t0: Optional[float] = None
        t_end: Optional[float] = None
        for e in events:
            if e["type"] == "trace_session_start":
                t0 = e["timestamp"]
            elif e["type"] == "trace_session_end":
                t_end = e["timestamp"]

        total_duration = (t_end - t0) if (t0 is not None and t_end is not None) else None

        ops: List[Dict[str, Any]] = []
        pending: Dict[str, Dict[str, Any]] = {}

        for e in events:
            if e["type"] != "operator_execute":
                continue

            oid = e.get("operator_id", "")
            phase = e.get("phase")
            name = e.get("operator_name", "unknown")
            ts = e["timestamp"]

            if phase == "start":
                pending[oid] = {
                    "operator_name": name,
                    "operator_id": oid,
                    "wall_start": ts - t0 if t0 is not None else ts,
                    "wall_end": ts - t0 if t0 is not None else ts,
                    "rows_out": 0,
                    "duration_ns": 0,
                    "produced_rows": False,
                }
                continue

            row = pending.pop(oid, None)
            if row is None:
                row = {
                    "operator_name": name,
                    "operator_id": oid,
                    "wall_start": ts - t0 if t0 is not None else ts,
                    "wall_end": ts - t0 if t0 is not None else ts,
                    "rows_out": 0,
                    "duration_ns": 0,
                    "produced_rows": False,
                }

            row["wall_end"] = ts - t0 if t0 is not None else ts
            row["rows_out"] = e.get("rows_out", 0) or 0
            row["duration_ns"] = e.get("duration_ns", 0) or 0
            row["produced_rows"] = e.get("produced_rows", True)
            ops.append(row)

        ops.sort(key=lambda row: (row.get("wall_start", 0), row.get("operator_name", "")))
        return ops, t0, total_duration

    def operator_profiles(self) -> List[Dict[str, Any]]:
        """Return per-operator aggregated stats for the EXPLAIN ANALYZE profile chart.

        Each entry covers one operator instance (unique operator_id) and contains
        totals aggregated across all trace events: CPU time, rows in/out, call count.
        Operators are ordered by first appearance (plan order, shallowest first).
        """
        events = self._load_events()
        id_to_name: Dict[str, str] = {}
        id_order: List[str] = []
        agg: Dict[str, Dict] = {}

        for e in events:
            if e.get("type") != "operator_execute":
                continue
            oid = e.get("operator_id", "")
            if oid not in id_to_name:
                id_to_name[oid] = e.get("operator_name", "unknown")
                id_order.append(oid)
                agg[oid] = {
                    "total_duration_ns": 0,
                    "total_rows_in": 0,
                    "total_rows_out": 0,
                    "call_count": 0,
                    "producing_calls": 0,
                }
            s = agg[oid]
            s["total_duration_ns"] += e.get("duration_ns", 0) or 0
            s["total_rows_in"] += e.get("rows_in", 0) or 0
            s["total_rows_out"] += e.get("rows_out", 0) or 0
            s["call_count"] += 1
            if e.get("produced_rows", True):
                s["producing_calls"] += 1

        result = []
        for oid in id_order:
            s = agg[oid]
            rows_in = s["total_rows_in"]
            rows_out = s["total_rows_out"]
            selectivity = (rows_out / rows_in * 100.0) if rows_in > 0 else None
            result.append(
                {
                    "operator_id": oid,
                    "operator_name": id_to_name[oid],
                    "total_duration_ns": s["total_duration_ns"],
                    "total_rows_in": rows_in,
                    "total_rows_out": rows_out,
                    "call_count": s["call_count"],
                    "producing_calls": s["producing_calls"],
                    "selectivity": round(selectivity, 4) if selectivity is not None else None,
                }
            )
        return result

    # ---------------------------------------------------------------------
    # Additional helpers for richer event inspection
    def events_for_file(self, file_id: str):
        """Return all events related to *file_id* (exact match)."""
        return [e for e in self._load_events() if e.get("file_id") == file_id]

    def events_by_component(self, component: str):
        """Return all events tagged with a specific component string."""
        return [e for e in self._load_events() if e.get("component") == component]

    def events_for_row_group(self, file_id: str, rg_idx: int):
        """Return events that include both *file_id* and a matching *rg_idx*."""
        return [
            e
            for e in self._load_events()
            if e.get("file_id") == file_id and e.get("rg_idx") == rg_idx
        ]

    def statistics(self) -> Dict[str, Any]:
        """
        Compute statistics from the trace.

        Returns:
            Dictionary with computed metrics:
            - total_files: number of files processed
            - total_bytes: total bytes downloaded
            - total_rows: total rows decoded
            - download_phase_duration_ms: time from first download_start to last download_complete
            - decode_phase_duration_ms: time from first decode_start to last decode_complete
            - query_duration_ms: total time from first to last event
            - max_concurrent_downloads: peak files downloading simultaneously
            - avg_download_time_ms: average per-file download time
            - avg_decode_time_ms: average per-file decode time
        """
        events = self._load_events()
        if not events:
            return {
                "total_files": 0,
                "total_bytes": 0,
                "total_rows": 0,
                "total_operations": 0,
                "total_download_ops": 0,
                "total_decode_ops": 0,
                "footer_download_ops": 0,
                "rowgroup_download_ops": 0,
                "rowgroup_decode_ops": 0,
                "download_phase_duration_ms": 0,
                "decode_phase_duration_ms": 0,
                "query_duration_ms": 0,
                "max_concurrent_downloads": 0,
                "avg_download_time_ms": 0,
                "avg_decode_time_ms": 0,
                "download_ops_by_component": {},
                "download_bytes_by_component": {},
                "decode_ops_by_component": {},
                "max_concurrent_downloads_by_component": {},
            }

        operations = self.operation_timelines()
        file_ids = {
            e.get("file_id")
            for e in events
            if e.get("type") == "file_discovered" and e.get("file_id")
        }
        if not file_ids:
            file_ids = {e.get("file_id") for e in events if e.get("file_id")}

        download_events = [
            e for e in events if e.get("type") in ("download_start", "download_complete")
        ]
        decode_events = [e for e in events if e.get("type") in ("decode_start", "decode_complete")]
        download_complete_events = [e for e in events if e.get("type") == "download_complete"]
        decode_complete_events = [e for e in events if e.get("type") == "decode_complete"]

        total_files = len(file_ids)
        total_bytes = sum(int(e.get("bytes_received") or 0) for e in download_complete_events)
        total_rows = sum(int(e.get("rows_decoded") or 0) for e in decode_complete_events)

        timestamps = [
            e.get("timestamp") for e in events if isinstance(e.get("timestamp"), (int, float))
        ]
        query_duration_ms = (max(timestamps) - min(timestamps)) * 1000 if timestamps else 0

        download_starts = [e.get("timestamp") for e in events if e.get("type") == "download_start"]
        download_ends = [e.get("timestamp") for e in events if e.get("type") == "download_complete"]
        download_phase_duration_ms = (
            (max(download_ends) - min(download_starts)) * 1000
            if download_starts and download_ends
            else 0
        )

        decode_starts = [e.get("timestamp") for e in events if e.get("type") == "decode_start"]
        decode_ends = [e.get("timestamp") for e in events if e.get("type") == "decode_complete"]
        decode_phase_duration_ms = (
            (max(decode_ends) - min(decode_starts)) * 1000 if decode_starts and decode_ends else 0
        )

        download_durations = [
            (op["download_complete"] - op["download_start"]) * 1000
            for op in operations
            if op.get("download_start") is not None and op.get("download_complete") is not None
        ]
        avg_download_time_ms = (
            sum(download_durations) / len(download_durations) if download_durations else 0
        )

        decode_durations = [
            (op["decode_complete"] - op["decode_start"]) * 1000
            for op in operations
            if op.get("decode_start") is not None and op.get("decode_complete") is not None
        ]
        avg_decode_time_ms = (
            sum(decode_durations) / len(decode_durations) if decode_durations else 0
        )

        download_ops_by_component: Dict[str, int] = defaultdict(int)
        download_bytes_by_component: Dict[str, int] = defaultdict(int)
        for event in download_complete_events:
            component = self._normalized_component(event, "download")
            download_ops_by_component[component] += 1
            download_bytes_by_component[component] += int(event.get("bytes_received") or 0)

        decode_ops_by_component: Dict[str, int] = defaultdict(int)
        for event in decode_complete_events:
            component = self._normalized_component(event, "decode")
            if component == "column":
                continue
            decode_ops_by_component[component] += 1

        max_concurrent = self._compute_max_concurrency_from_events(download_events)
        max_concurrent_downloads_by_component: Dict[str, int] = {}
        for component in set(download_ops_by_component):
            component_events = [
                e for e in download_events if self._normalized_component(e, "download") == component
            ]
            max_concurrent_downloads_by_component[component] = (
                self._compute_max_concurrency_from_events(component_events)
            )

        total_download_ops = sum(download_ops_by_component.values())
        total_decode_ops = sum(decode_ops_by_component.values())

        return {
            "total_files": total_files,
            "total_bytes": total_bytes,
            "total_rows": total_rows,
            "total_operations": len(operations),
            "total_download_ops": total_download_ops,
            "total_decode_ops": total_decode_ops,
            "footer_download_ops": download_ops_by_component.get("footer", 0),
            "rowgroup_download_ops": download_ops_by_component.get("rowgroup", 0),
            "rowgroup_decode_ops": decode_ops_by_component.get("rowgroup", 0),
            "download_phase_duration_ms": download_phase_duration_ms,
            "decode_phase_duration_ms": decode_phase_duration_ms,
            "query_duration_ms": query_duration_ms,
            "max_concurrent_downloads": max_concurrent,
            "avg_download_time_ms": avg_download_time_ms,
            "avg_decode_time_ms": avg_decode_time_ms,
            "download_ops_by_component": dict(download_ops_by_component),
            "download_bytes_by_component": dict(download_bytes_by_component),
            "decode_ops_by_component": dict(decode_ops_by_component),
            "max_concurrent_downloads_by_component": max_concurrent_downloads_by_component,
        }

    def _compute_max_concurrency(
        self, timelines: Dict[str, Dict[str, Any]], start_key: str, end_key: str
    ) -> int:
        """Compute max number of overlapping operations."""
        events = []

        for timeline in timelines.values():
            if start_key in timeline and end_key in timeline:
                events.append((timeline[start_key], 1))  # Start
                events.append((timeline[end_key], -1))  # End

        if not events:
            return 0

        events.sort()
        max_concurrent = 0
        current = 0

        for _, delta in events:
            current += delta
            max_concurrent = max(max_concurrent, current)

        return max_concurrent

    @staticmethod
    def _compute_max_concurrency_from_events(events: List[Dict[str, Any]]) -> int:
        """Compute max concurrency directly from raw start/complete events."""
        timeline_points: List[tuple] = []
        for event in events:
            timestamp = event.get("timestamp")
            if not isinstance(timestamp, (int, float)):
                continue
            if event.get("type") == "download_start":
                timeline_points.append((timestamp, 1))
            elif event.get("type") == "download_complete":
                timeline_points.append((timestamp, -1))

        if not timeline_points:
            return 0

        # End events are applied before starts at the same timestamp.
        timeline_points.sort(key=lambda point: (point[0], point[1]))
        current = 0
        maximum = 0
        for _, delta in timeline_points:
            current += delta
            maximum = max(maximum, current)
        return maximum
