"""A band join's realized value range bounds the OTHER leg, shifted by the band's offset.

CorrelatedFiltersStrategy reads each join key's propagated range and pushes it onto
the opposite leg's scan as a necessary condition for a match. That argument was
implemented for equi-joins only, but it never depended on equality:

    l.event_time <= f.flow_start
    l.event_time  > f.flow_start - INTERVAL '20' SECOND     f.flow_start in [lo, hi]

    => any matching l.event_time is in (lo - 20s, hi]

Same necessary condition, bounds displaced by the offset. An equi-join is the
zero-offset case that happens to establish BOTH ends at once; a band establishes
one end per conjunct.

WHAT THIS FILE PINS

A shifted bound that is off by one tick, or shifted the wrong way, DELETES JOINED
ROWS. Nothing raises, no count looks implausible, and the answer stays perfectly
self-consistent — it is simply missing rows. So every query here is compared
row-for-row against TWO oracles: the same query with CorrelatedFiltersStrategy
switched off, and the same query with PredicatePushdownStrategy switched off (where
the band is a Filter above the join and no range can be derived at all).

The rows that matter are the WINDOW EDGES, and the fixture puts one ONE MICROSECOND
either side of every bound the optimizer computes. `lo_plus1us` is the sharp one: it
sits one microsecond inside the derived lower bound, so ANY understatement of the
20-second shift drops it. `test_the_ranges_are_actually_pushed` exists because
without it every assertion above would still pass if the rule quietly declined
everything — which is exactly what it did for temporal columns before this change.

DAY BOUNDARIES: `flows.a` starts at 00:00:10, so its -20s bound lands on the
PREVIOUS day at 23:59:50, and `flows.d`'s window opens the evening before. A shift
computed in the wrong unit — days read as microseconds, the "silent 1970 bound" —
cannot survive either.

Fixture: `testdata/band_join/`, regenerated by `dev/generate_band_join_fixture.py`.
It is a real parquet scan on purpose: this rule needs a connector, footer min/max
and propagated statistics, so a VALUES relation would exercise none of it.

Related: `test_band_join_absorption.py`, which pins the step BEFORE this one — a
cross-relation band in the WHERE reaching the join's ON at all.
"""

import datetime
import os
import sys

import pytest

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import opteryx
from opteryx import config
from opteryx.planner.optimizer.strategies.correlated_filters import _coerce_temporal_bound
from opteryx.planner.optimizer.strategies.correlated_filters import _resolve_offset
from opteryx.planner.optimizer.strategies.correlated_filters import _shifted
from opteryx.planner.optimizer.statistics import ColumnRange
from opteryx.types.logical_type import DATE
from opteryx.types.logical_type import INT64
from opteryx.types.logical_type import TIMESTAMP
from opteryx.types.logical_type import TIME
from opteryx.types.logical_type import TimestampUnit

FLOWS = "testdata.band_join.flows"
LOOKUPS = "testdata.band_join.lookups"

# `l.event_time` in (min(flow_start) - 20s, max(flow_start)] is the necessary
# condition; both ends are transported, from two separate conjuncts.
TIMESTAMP_BAND = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_time <= f.flow_start
   AND l.event_time > f.flow_start - INTERVAL '20' SECOND
 ORDER BY l.tag
"""

# Only the upper end exists here, so only the upper bound may be transported.
TIMESTAMP_ONE_SIDED = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_time <= f.flow_start
 ORDER BY l.tag
"""

# DATE32 counts DAYS, so the INTERVAL's microseconds must be divided down before
# they can be added to a bound. Getting that wrong is the "silent 1970" bound.
DATE_BAND = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_day <= f.flow_day
   AND l.event_day >= f.flow_day - INTERVAL '2' DAY
 ORDER BY l.tag
"""

# A sub-day offset on a DATE column has no exact day-unit spelling, and a MONTH is
# not a fixed displacement at all (the calendar kernel clamps to end-of-month). Both
# must DECLINE the shift rather than round it — and still answer correctly.
DATE_SUB_DAY_OFFSET = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_day <= f.flow_day
   AND l.event_day >= f.flow_day - INTERVAL '12' HOUR
 ORDER BY l.tag
"""

TIMESTAMP_MONTH_OFFSET = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_time <= f.flow_start
   AND l.event_time > f.flow_start - INTERVAL '1' MONTH
 ORDER BY l.tag
"""

# The zero-offset case. Both bounds, exactly as before this change.
EQUI = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_time = f.flow_start
 ORDER BY l.tag
"""

# A preserved-side row that matches nothing must survive NULL-extended, so a
# match-necessary condition may not be pushed onto EITHER leg of an outer join.
# (This query's WHERE is inner-like — `NULL <= x` is false — but the join itself
# must still not be narrowed, and `visit` admits only inner / nested loop.)
OUTER_BAND = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f LEFT OUTER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_time <= f.flow_start
   AND l.event_time > f.flow_start - INTERVAL '20' SECOND
 ORDER BY l.tag
"""

# The inexact offsets ALONE. Written with the `<=` conjunct alongside them (as
# `DATE_BAND` is) the zero-offset half would push legitimately and mask the
# decline, so these carry the one conjunct whose shift cannot be expressed.
ONLY_SUB_DAY_OFFSET = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_day >= f.flow_day - INTERVAL '12' HOUR
 ORDER BY l.tag
"""

ONLY_MONTH_OFFSET = f"""
SELECT f.client, l.tag
  FROM {FLOWS} f INNER JOIN {LOOKUPS} l ON f.client = l.client
 WHERE l.event_time > f.flow_start - INTERVAL '1' MONTH
 ORDER BY l.tag
"""

ALL_QUERIES = (
    TIMESTAMP_BAND,
    TIMESTAMP_ONE_SIDED,
    DATE_BAND,
    DATE_SUB_DAY_OFFSET,
    TIMESTAMP_MONTH_OFFSET,
    ONLY_SUB_DAY_OFFSET,
    ONLY_MONTH_OFFSET,
    EQUI,
    OUTER_BAND,
)


def rows(sql):
    """Every row, in order, as tuples — row-for-row comparison, not a count."""
    session = opteryx.session()
    out = []
    for morsel in session.execute_to_morsels(sql):
        if morsel is None:
            continue
        table = morsel.to_arrow().to_pydict()
        names = list(table.keys())
        out.extend(zip(*(table[name] for name in names)))
    return out


def rows_and_pushes(sql):
    """As `rows`, plus how many correlated range predicates the optimizer derived."""
    session = opteryx.session()
    out = []
    for morsel in session.execute_to_morsels(sql):
        if morsel is None:
            continue
        table = morsel.to_arrow().to_pydict()
        names = list(table.keys())
        out.extend(zip(*(table[name] for name in names)))
    return out, session.telemetry.get("optimization_inner_join_correlated_filter", 0)


@pytest.fixture
def without_correlated_filters():
    """The same plan with this rule switched off — every derived range removed, the
    join and its residual otherwise untouched. The tightest possible oracle."""
    original = config.features.disable_correlated_filters
    config.features.disable_correlated_filters = True
    try:
        yield rows
    finally:
        config.features.disable_correlated_filters = original


@pytest.fixture
def without_pushdown():
    """The same query with PredicatePushdownStrategy off, so the band never reaches
    the join's ON and no range can be derived from it at all."""
    original = config.features.disable_predicate_pushdown
    config.features.disable_predicate_pushdown = True
    try:
        yield rows
    finally:
        config.features.disable_predicate_pushdown = original


@pytest.mark.parametrize("sql", ALL_QUERIES)
def test_matches_the_plan_without_correlated_filters(sql, without_correlated_filters):
    assert rows(sql) == without_correlated_filters(sql), sql


@pytest.mark.parametrize("sql", ALL_QUERIES)
def test_matches_the_unoptimised_plan(sql, without_pushdown):
    assert rows(sql) == without_pushdown(sql), sql


def test_timestamp_band_window_edges():
    """`lo_plus1us` is one microsecond inside the derived lower bound and `hi_exact`
    sits exactly on the derived upper one; both must survive. `lo_exact` is on the
    OPEN end (`>`) and `a_plus1us` past the CLOSED one (`<=`), so both must not."""
    result = rows(TIMESTAMP_BAND)
    tags = {tag for _, tag in result}

    assert "lo_plus1us" in tags, result  # dies to any understated shift
    assert "lo_inside" in tags, result
    assert "a_exact" in tags, result  # `<=` is closed
    assert "hi_exact" in tags, result  # exactly on the transported upper bound
    assert "d_prev_evening" in tags, result  # window opens on the previous day

    assert "lo_exact" not in tags, result  # `>` is open
    assert "lo_minus1us" not in tags, result
    assert "a_plus1us" not in tags, result
    assert "hi_plus1us" not in tags, result
    assert "z_no_flow" not in tags, result  # no flow for this client at all

    assert result == [
        ("a", "a_exact"),
        ("a", "a_minus1us"),
        ("b", "b_inside"),
        ("b", "b_lo_plus1us"),
        ("c", "c_inside"),
        ("d", "d_exact"),
        ("d", "d_lo_plus1us"),
        ("d", "d_prev_evening"),
        ("e", "hi_exact"),
        ("e", "hi_minus1us"),
        ("a", "lo_inside"),
        ("a", "lo_plus1us"),
    ], result


def test_date_band_window_edges():
    """min(flow_day) is 2024-03-10, so the -2 day shift puts the derived lower bound
    on 2024-03-08 — `day_minus2` is ON it and `>=` is closed, so it must survive."""
    tags = {tag for _, tag in rows(DATE_BAND)}
    assert "day_minus2" in tags
    assert "day_minus1" in tags
    assert "day_minus3" not in tags


def test_the_ranges_are_actually_pushed():
    """Without this, every correctness assertion above passes vacuously — a rule that
    declines everything is trivially answer-preserving. Temporal columns declined
    exactly that way until the bound encoding was pinned down."""
    for sql in (TIMESTAMP_BAND, TIMESTAMP_ONE_SIDED, DATE_BAND, EQUI):
        _, pushes = rows_and_pushes(sql)
        assert pushes > 0, sql


def test_an_inexact_offset_declines_rather_than_rounds():
    """A half-day offset on a DATE column and a MONTH offset on a timestamp have no
    exact displacement in the target's unit. Declining costs pruning; rounding would
    cost rows."""
    for sql in (ONLY_SUB_DAY_OFFSET, ONLY_MONTH_OFFSET):
        _, pushes = rows_and_pushes(sql)
        assert pushes == 0, sql


def test_an_outer_join_gets_no_correlated_filter():
    """The pushed range is a necessary condition for a MATCH. An outer join emits its
    non-matching preserved rows NULL-extended, so narrowing either leg by it would
    delete rows that must survive. `visit` admits inner / nested loop only."""
    _, pushes = rows_and_pushes(OUTER_BAND)
    assert pushes == 0


# ---------------------------------------------------------------------------
# The bound arithmetic itself, without a query in the way.
# ---------------------------------------------------------------------------

TIMESTAMP_US = TIMESTAMP(TimestampUnit.MICROSECONDS)

from opteryx.expression.intervals import MICROSECONDS_PER_DAY as US_PER_DAY


def interval(months, microseconds):
    """A stand-in for an INTERVAL literal node: value plus the `type` tag
    `_resolve_offset` reads to tell an interval from a number."""

    class _Literal:
        def __init__(self):
            from opteryx.types.logical_type import INTERVAL

            self.value = (months, microseconds)
            self.type = INTERVAL

    return _Literal()


def number(value, column_type=INT64):
    class _Literal:
        def __init__(self):
            self.value = value
            self.type = column_type

    return _Literal()


def test_no_offset_resolves_to_zero():
    assert _resolve_offset([], TIMESTAMP_US) == 0
    assert _resolve_offset([], DATE) == 0
    assert _resolve_offset([], INT64) == 0


@pytest.mark.parametrize("sign", (1, -1))
def test_timestamp_offset_is_microseconds(sign):
    assert _resolve_offset([(interval(0, 20_000_000), sign)], TIMESTAMP_US) == sign * 20_000_000


@pytest.mark.parametrize("sign", (1, -1))
def test_date_offset_is_days(sign):
    """The INTERVAL carries microseconds; DATE32 counts days. Reading the µs count as
    a day count is the silent-1970 bug in its purest form."""
    assert _resolve_offset([(interval(0, 2 * US_PER_DAY), sign)], DATE) == sign * 2


def test_a_month_offset_declines():
    """`interval_apply_to_temporal` applies months as calendar arithmetic with
    end-of-month clamping — 31 days from January, 28 from February. No number
    describes it."""
    assert _resolve_offset([(interval(1, 0), 1)], TIMESTAMP_US) is None
    assert _resolve_offset([(interval(1, 0), 1)], DATE) is None
    assert _resolve_offset([(interval(1, US_PER_DAY), 1)], DATE) is None


def test_a_sub_day_offset_declines_on_a_date():
    assert _resolve_offset([(interval(0, US_PER_DAY // 2), 1)], DATE) is None
    # ... but is exact on a microsecond timestamp.
    assert _resolve_offset([(interval(0, US_PER_DAY // 2), 1)], TIMESTAMP_US) == US_PER_DAY // 2


def test_offsets_on_both_operands_combine():
    """`Lcol + dl <op> Rcol + dr` is `Lcol <op> Rcol + (dr - dl)`."""
    terms = [(interval(0, 5 * US_PER_DAY), 1), (interval(0, 2 * US_PER_DAY), -1)]
    assert _resolve_offset(terms, DATE) == 3


def test_a_numeric_offset_must_be_an_integer():
    assert _resolve_offset([(number(5), 1)], INT64) == 5
    assert _resolve_offset([(number(5), -1)], INT64) == -5
    # A float offset makes the sum a rounding question whose safe direction depends
    # on which bound is being shifted; declining is the sound answer.
    from opteryx.types.logical_type import FLOAT64

    assert _resolve_offset([(number(0.5, FLOAT64), 1)], FLOAT64) is None


def test_an_interval_offset_declines_on_a_number_and_a_number_on_a_temporal():
    assert _resolve_offset([(interval(0, US_PER_DAY), 1)], INT64) is None
    assert _resolve_offset([(number(5), 1)], TIMESTAMP_US) is None
    assert _resolve_offset([(number(5), 1)], DATE) is None


def test_shift_crosses_a_day_boundary_in_both_directions():
    """2024-03-10 00:00:10 UTC, shifted back 20 seconds, is on 2024-03-09."""
    start = datetime.datetime(2024, 3, 10, 0, 0, 10, tzinfo=datetime.timezone.utc)
    start_us = int(start.timestamp()) * 1_000_000
    shifted = _shifted(ColumnRange(lower_bound=start_us, upper_bound=start_us), -20_000_000, "both")
    expected = datetime.datetime(2024, 3, 9, 23, 59, 50, tzinfo=datetime.timezone.utc)
    assert shifted.lower_bound == int(expected.timestamp()) * 1_000_000
    assert shifted.upper_bound == shifted.lower_bound

    forward = _shifted(ColumnRange(lower_bound=start_us, upper_bound=start_us), +20_000_000, "both")
    assert forward.lower_bound == start_us + 20_000_000

    # DATE32, in days, over the same boundary.
    march_10 = (datetime.date(2024, 3, 10) - datetime.date(1970, 1, 1)).days
    back = _shifted(ColumnRange(lower_bound=march_10, upper_bound=march_10), -2, "both")
    assert back.lower_bound == (datetime.date(2024, 3, 8) - datetime.date(1970, 1, 1)).days


def test_shift_keeps_only_the_bound_the_comparator_establishes():
    original = ColumnRange(lower_bound=10, upper_bound=20)
    assert _shifted(original, 5, "both") == ColumnRange(lower_bound=15, upper_bound=25)
    assert _shifted(original, 5, "upper") == ColumnRange(lower_bound=None, upper_bound=25)
    assert _shifted(original, 5, "lower") == ColumnRange(lower_bound=15, upper_bound=None)
    # A one-sided source range narrowed to its missing end has nothing to transport.
    assert _shifted(ColumnRange(lower_bound=10, upper_bound=None), 5, "upper") is None


def test_temporal_bounds_are_carried_in_their_native_encoding():
    """`value_range` holds the column's native int — microseconds for TIMESTAMP64,
    days for DATE32 — and `build_literal_node` passes an int through untouched, so
    the coercion is an identity. No datetime is ever constructed, which is what keeps
    the DATE32-read-as-microseconds bound out of this path."""
    from opteryx.types.logical_type import LogicalCategory

    assert (
        _coerce_temporal_bound(1_710_028_790_000_000, TIMESTAMP_US, LogicalCategory.TIMESTAMP)
        == 1_710_028_790_000_000
    )
    assert _coerce_temporal_bound(19_790, DATE, LogicalCategory.DATE) == 19_790

    # A float bound would mean an inlet wrote a value `value_range` does not hold.
    assert _coerce_temporal_bound(19_790.0, DATE, LogicalCategory.DATE) is None
    # Out of the physical width — the literal would die on materialisation.
    assert _coerce_temporal_bound(2**31, DATE, LogicalCategory.DATE) is None
    assert _coerce_temporal_bound(-(2**31) - 1, DATE, LogicalCategory.DATE) is None
    # A non-microsecond timestamp declines because the two inlets of `value_range`
    # disagree on its unit: the manifest contributes the footer's raw milliseconds,
    # while a bound harvested from a predicate literal is microseconds (
    # `build_literal_node` runs `timestamp_to_int64_us` regardless of the declared
    # unit). The bound's unit is therefore not knowable from its type.
    assert (
        _coerce_temporal_bound(
            1_710_028_790_000, TIMESTAMP(TimestampUnit.MILLISECONDS), LogicalCategory.TIMESTAMP
        )
        is None
    )


def test_time_columns_never_receive_a_pushed_bound():
    """TIME has no working column type in this engine — a scan yields raw ints, CAST
    yields raw ticks, and the operator map has no TIME rows. A bound pushed onto one
    would be compared in a space nothing else agrees on."""
    from opteryx.planner.optimizer.strategies.correlated_filters import _coerce_bound

    assert _coerce_bound(1_000_000, TIME(), True) is None
    assert _coerce_bound(1_000_000, TIME(), False) is None


if __name__ == "__main__":  # pragma: no cover
    from tests import run_tests

    run_tests()
