#!/usr/bin/env python3
"""
Import function cost estimates back into the function catalog.

This script reads cost estimates from a JSON file (generated by estimate_function_costs.py)
and updates the function definitions in the source code.

Usage:
    python import_function_costs.py function_costs.json [--apply]

The script can:
1. Preview the changes (default, without --apply)
2. Apply changes directly to source files (with --apply)
3. Generate a Python patch file to apply manually
"""

import argparse
import json
import re
from pathlib import Path
from typing import Any
from typing import Dict
from typing import Tuple


class CostImporter:
    """Import cost estimates and apply them to function definitions."""

    def __init__(self, costs_file: Path):
        """Initialize importer from costs JSON file.

        Args:
            costs_file: Path to JSON file generated by estimate_function_costs.py
        """
        with open(costs_file) as f:
            self.cost_data = json.load(f)

        # Build lookup: (function_name, kernel_id) -> cost_us_per_million
        self.costs: Dict[Tuple[str, str], float] = {}
        for func_name, kernels in self.cost_data.get("functions", {}).items():
            for kernel_info in kernels:
                key = (func_name, kernel_info["kernel_id"])
                self.costs[key] = kernel_info["cost_us_per_million"]

    def find_function_definitions(self) -> Dict[str, Path]:
        """Find all Python files containing function definitions.

        Returns:
            Dictionary mapping function name to file path
        """
        func_files = {}

        # Search for function implementations
        implementations_dir = Path(
            "/Users/justin/Nextcloud/opteryx-core/opteryx/expression/functions/implementations"
        )

        if implementations_dir.exists():
            for py_file in implementations_dir.glob("*.py"):
                if py_file.name == "__init__.py":
                    continue

                content = py_file.read_text()
                # Look for function definitions (crude pattern)
                for match in re.finditer(r'FunctionDefinition\(\s*name\s*=\s*["\']([A-Z_]+)["\']', content):
                    func_name = match.group(1)
                    func_files[func_name] = py_file

        return func_files

    def preview_changes(self) -> str:
        """Generate a preview of what would be changed.

        Returns:
            Formatted string showing proposed changes
        """
        lines = ["PREVIEW: Proposed Cost Updates\n"]
        lines.append("=" * 80 + "\n")

        for (func_name, kernel_id), cost in sorted(self.costs.items()):
            lines.append(
                f"{func_name:<20} {kernel_id:<25} {cost:>15.2f} μs/million rows\n"
            )

        lines.append("=" * 80 + "\n")
        lines.append(f"Total updates: {len(self.costs)}\n")

        return "".join(lines)

    def generate_patch(self) -> str:
        """Generate a Python-format patch showing the updates.

        Returns:
            String with code showing old vs new cost values
        """
        lines = ["# Function Cost Updates\n\n"]
        lines.append("# Before/After cost_us_per_million values:\n\n")

        for (func_name, kernel_id), cost in sorted(self.costs.items()):
            lines.append(f"# {func_name} ({kernel_id}):\n")
            lines.append(f"# OLD: cost_us_per_million=0.0\n")
            lines.append(f"# NEW: cost_us_per_million={cost:.2f}\n\n")

        return "".join(lines)

    def apply_updates(self, dry_run: bool = True) -> Dict[str, Any]:
        """Apply cost updates to function definition files.

        This is a conservative approach that:
        1. Finds KernelSpec definitions
        2. Updates cost_us_per_million values
        3. Optionally writes changes back to files

        Args:
            dry_run: If True, don't write files, just return what would change

        Returns:
            Dictionary with update results
        """
        results = {
            "dry_run": dry_run,
            "files_modified": 0,
            "kernels_updated": 0,
            "updates": [],
        }

        func_files = self.find_function_definitions()

        # For each function file, look for KernelSpec definitions
        kernel_spec_pattern = re.compile(
            r'KernelSpec\(\s*id\s*=\s*["\']([^"\']+)["\']([^)]*?)cost_us_per_million\s*=\s*([\d.]+)',
            re.DOTALL,
        )

        for func_name, file_path in func_files.items():
            content = file_path.read_text()
            original_content = content

            # Find all KernelSpec definitions in this file
            for match in kernel_spec_pattern.finditer(content):
                kernel_id = match.group(1)
                old_cost_str = match.group(3)
                old_cost = float(old_cost_str)

                # Look up new cost
                key = (func_name, kernel_id)
                if key in self.costs:
                    new_cost = self.costs[key]

                    if new_cost != old_cost:
                        # Replace the cost value
                        old_value = f"cost_us_per_million={old_cost_str}"
                        new_value = f"cost_us_per_million={new_cost:.2f}"

                        content = content.replace(old_value, new_value, 1)

                        results["kernels_updated"] += 1
                        results["updates"].append({
                            "file": str(file_path),
                            "function": func_name,
                            "kernel_id": kernel_id,
                            "old_cost": old_cost,
                            "new_cost": new_cost,
                        })

            # Write file if changes were made
            if content != original_content:
                if not dry_run:
                    file_path.write_text(content)
                results["files_modified"] += 1

        return results


def main():
    parser = argparse.ArgumentParser(
        description="Import function cost estimates into the function catalog"
    )
    parser.add_argument(
        "costs_file",
        type=Path,
        help="JSON file with cost estimates (from estimate_function_costs.py)",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply changes to source files (default: dry-run preview)",
    )
    parser.add_argument(
        "--patch",
        action="store_true",
        help="Generate a patch file instead of applying changes",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output file for patch (used with --patch)",
    )

    args = parser.parse_args()

    if not args.costs_file.exists():
        print(f"Error: Cost file not found: {args.costs_file}")
        return 1

    importer = CostImporter(args.costs_file)

    if args.patch:
        # Generate and save patch
        patch_content = importer.generate_patch()
        output_path = args.output or Path("function_costs.patch")

        output_path.write_text(patch_content)
        print(f"Patch written to: {output_path}")
        print(f"\n{patch_content}")
        return 0

    # Show preview
    print(importer.preview_changes())

    if args.apply:
        print("\nApplying updates...\n")
        results = importer.apply_updates(dry_run=False)

        print(f"Files modified: {results['files_modified']}")
        print(f"Kernels updated: {results['kernels_updated']}")

        if results["updates"]:
            print("\nUpdated costs:")
            for update in results["updates"]:
                print(
                    f"  {update['function']} ({update['kernel_id']}): "
                    f"{update['old_cost']:.2f} → {update['new_cost']:.2f}"
                )
        return 0
    else:
        print("\nRun with --apply to update source files")
        print("Or use --patch to generate a patch file")
        return 0


if __name__ == "__main__":
    main()
