# cython: language_level=3
# cython: nonecheck=False
# cython: cdivision=True

"""
Plan-time regex -> byte-level DFA compiler.

RE2's *parser* (`re2::Regexp::Parse`) is the only RE2 surface used here — it
builds the rune-level AST, which this file lowers into a Thompson NFA and
then determinises (subset construction) into a byte-transition-table DFA.
RE2's own matcher (Prog/DFA/NFA/bitstate/onepass, RE2::PartialMatch) is never
called. This is "the planner" role described in `.claude/CLAUDE.md`: Python,
plan-time only. The compiled blob is walked by a pure table-lookup loop at
execution time (`vector_rlike.pyx`, `vector_anyop_like.pyx`) — no RE2, no
backtracking, no Python, one byte read + one array index per input byte.

Scope, deliberate and precedented (matches `vector_dfa_extract.pyx`'s own
`_is_ascii_literal_regexp` restriction):
  - Pattern literals and character-class ranges must be ASCII (rune <= 127).
    Subject strings can be arbitrary UTF-8 — ASCII bytes never appear inside
    a multi-byte UTF-8 sequence, so byte-level matching of an ASCII pattern
    against UTF-8 bytes is exact. A pattern containing non-ASCII text is
    refused (returns None), not silently mishandled.
  - Case-insensitive patterns (`(?i)`, `FoldCase`) are refused. Not yet
    implemented; refusing beats silently matching case-sensitively.
  - `^`/`$` are only recognised at the outermost start/end of the pattern
    (`^foo$`, `^foo`, `foo$`), not nested inside alternation/repetition
    (`(^foo|bar$)` is refused) — same restriction the existing DFA_EXTRACT
    compiler already applies for the same reason: correctly handling nested
    anchors requires per-branch position tracking this table format doesn't
    carry, and the outermost-only case covers the overwhelming majority of
    real patterns.
  - `.` (AnyChar) matches any single byte except newline — a byte, not a
    Unicode codepoint. For boolean PartialMatch-style matching this gives
    the same yes/no answer as codepoint-aware `.` on any pattern that
    doesn't rely on `.` counting exact character positions (`.{3}` against
    a multi-byte-UTF-8 subject counts bytes, not codepoints) — a documented
    divergence, not a silent one.
  - Bounded repeat `{n,m}` is unrolled; construction aborts (returns None)
    past a fixed size cap, same as the overall DFA state-count cap below.

Blob format (little-endian, all multi-byte fields):
    u8  version (=1)
    u8  flags (bit0 = anchored_start: no implicit "search anywhere" self-loop
               on the start state; bit1 = anchored_end: only check the
               accept flag after the LAST input byte, not after every byte)
    u16 num_states
    accept_bitmap: ceil(num_states / 8) bytes, bit i set => state i accepts
    transition table: num_states * 256 * u16 (next-state index)
Start state is always state 0.
"""

from libc.stdint cimport uint8_t, uint16_t
from cpython.bytes cimport PyBytes_AsStringAndSize
from libcpp.string cimport string

# Duplicated verbatim from vector_dfa_extract.pyx rather than shared via a
# .pxd: both files are textually `include`d into one consolidated module
# (opteryx.compiled.vector_ops, generated by setup.py's
# generate_consolidated_module) and a shared-.pxd cimport of this enum
# produced unresolved-identifier errors in that merged-compilation-unit
# build (cimported enum members did not propagate the way a plain Python
# import would across textually included content) — duplication is the
# working option, at the cost of a "redeclared" warning from the C++
# compiler, which is harmless (same underlying re2:: types either way).
cdef extern from "re2/stringpiece.h" namespace "re2":
    cdef cppclass StringPiece:
        StringPiece() except +
        StringPiece(const char* data, size_t length) except +

cdef extern from "re2/regexp.h" namespace "re2":
    cdef enum RegexpOp:
        kRegexpNoMatch
        kRegexpEmptyMatch
        kRegexpLiteral
        kRegexpLiteralString
        kRegexpConcat
        kRegexpAlternate
        kRegexpStar
        kRegexpPlus
        kRegexpQuest
        kRegexpRepeat
        kRegexpCapture
        kRegexpAnyChar
        kRegexpAnyByte
        kRegexpBeginLine
        kRegexpEndLine
        kRegexpWordBoundary
        kRegexpNoWordBoundary
        kRegexpBeginText
        kRegexpEndText
        kRegexpCharClass
        kRegexpHaveMatch

    cdef cppclass RegexpStatus:
        RegexpStatus() except +
        bint ok() const
        string Text() const

    cdef struct RuneRange:
        int lo
        int hi

    cdef cppclass CharClass:
        int size()
        RuneRange* begin()
        RuneRange* end()

    cdef cppclass Regexp:
        RegexpOp op()
        int nsub()
        Regexp** sub()
        int min()
        int max()
        int cap()
        int nrunes()
        int parse_flags()
        int rune()
        int* runes()
        CharClass* cc()
        Regexp* Incref()
        void Decref()
        Regexp* Simplify()
        @staticmethod
        Regexp* Parse(const StringPiece& s, RegexpParseFlags flags, RegexpStatus* status)

cdef extern from "re2/regexp.h" namespace "re2::Regexp":
    cdef enum RegexpParseFlags "re2::Regexp::ParseFlags":
        NoParseFlags
        FoldCase
        Literal
        ClassNL
        DotNL
        MatchNL
        OneLine
        Latin1
        NonGreedy
        PerlClasses
        PerlB
        PerlX
        UnicodeGroups
        NeverNL
        NeverCapture
        LikePerl

# ---------------------------------------------------------------------------
# NFA construction (Thompson's construction). Pure Python objects — this
# module only runs at plan time, correctness and clarity matter, raw speed
# does not.
# ---------------------------------------------------------------------------

DFA_STATE_CAP = 512
_REPEAT_UNROLL_CAP = 1000


class _TooComplex(Exception):
    """Internal signal: abandon compilation, caller returns None."""


class _Nfa:
    __slots__ = ("eps", "trans")

    def __init__(self):
        self.eps = set()
        self.trans = {}


class _NfaBuilder:
    def __init__(self):
        self.states = []

    def new_state(self):
        self.states.append(_Nfa())
        return len(self.states) - 1

    def frag_byte_set(self, byte_set):
        s0 = self.new_state()
        s1 = self.new_state()
        trans = self.states[s0].trans
        for b in byte_set:
            trans[b] = s1
        return s0, {s1}

    def frag_concat(self, a, b):
        a_start, a_accepts = a
        b_start, b_accepts = b
        for acc in a_accepts:
            self.states[acc].eps.add(b_start)
        return a_start, b_accepts

    def frag_alt(self, a, b):
        a_start, a_accepts = a
        b_start, b_accepts = b
        s0 = self.new_state()
        self.states[s0].eps.add(a_start)
        self.states[s0].eps.add(b_start)
        return s0, a_accepts | b_accepts

    def frag_star(self, a):
        a_start, a_accepts = a
        s0 = self.new_state()
        self.states[s0].eps.add(a_start)
        for acc in a_accepts:
            self.states[acc].eps.add(a_start)
        return s0, a_accepts | {s0}

    def frag_plus(self, a):
        a_start, a_accepts = a
        for acc in a_accepts:
            self.states[acc].eps.add(a_start)
        return a_start, a_accepts

    def frag_quest(self, a):
        a_start, a_accepts = a
        return a_start, a_accepts | {a_start}


cdef bint _rune_ascii(int rune) noexcept:
    return 0 <= rune <= 127


cdef int _UNICODE_MAX_RUNE = 1114111


cdef object _charclass_byte_set(CharClass* cc):
    """Byte-set for a char class's ranges. Ranges fully within ASCII map
    directly. A range unbounded at the top (hi == Unicode max) — the shape
    RE2 produces for `.` and any `[^...]` negation, since it always
    represents "the rest of the codepoint space" — is byte-approximated as
    "every non-ASCII byte (0x80-0xFF) plus whatever ASCII portion of the
    range falls at/below 127". This is safe for the same reason `.`'s
    any-byte-except-newline handling is safe (see module docstring): every
    excluded/included boundary here is an ASCII byte, and ASCII bytes never
    appear inside a multi-byte UTF-8 sequence, so byte-level inclusion of
    0x80-0xFF exactly matches "any non-ASCII codepoint" for partial-match
    purposes. A range that is non-ASCII but bounded at the top (e.g. a
    specific Unicode block) has no safe byte-level equivalent and is
    refused, same as before.
    """
    cdef RuneRange* it
    cdef RuneRange* end
    cdef int lo_ascii
    result = set()
    if cc == NULL:
        return None
    it = cc.begin()
    end = cc.end()
    while it != end:
        if it.lo < 0:
            return None
        if it.hi <= 127:
            for b in range(it.lo, it.hi + 1):
                result.add(b)
        elif it.hi == _UNICODE_MAX_RUNE:
            lo_ascii = it.lo if it.lo <= 127 else 128
            for b in range(lo_ascii, 128):
                result.add(b)
            for b in range(128, 256):
                result.add(b)
        else:
            return None
        it += 1
    return result


cdef object _build_fragment(object nb, Regexp* re):
    """Recursively lower an RE2 AST node into an NFA fragment
    (start_state, accept_state_set). Raises _TooComplex for anything outside
    the supported/ASCII/no-fold scope described in the module docstring."""
    cdef int i
    cdef int lo
    cdef int hi
    cdef int n
    cdef Regexp* child

    if re == NULL:
        raise _TooComplex("null node")

    if (re.parse_flags() & FoldCase) != 0:
        raise _TooComplex("case-insensitive pattern")

    op = re.op()

    if op == kRegexpEmptyMatch:
        # Empty regex (e.g. `''`, or an empty alternation branch `a|`) matches
        # the empty string at any position — a single state that is both start
        # and accept, with no transitions. Combined with the unanchored-search
        # self-loop this makes the whole pattern match every subject, exactly
        # as re.search('', s) does.
        empty_state = nb.new_state()
        return empty_state, {empty_state}

    if op == kRegexpLiteral:
        rune = re.rune()
        if not _rune_ascii(rune):
            raise _TooComplex("non-ASCII literal")
        return nb.frag_byte_set({rune})

    if op == kRegexpLiteralString:
        n = re.nrunes()
        if n == 0:
            raise _TooComplex("empty literal string")
        frag = None
        for i in range(n):
            rune = re.runes()[i]
            if not _rune_ascii(rune):
                raise _TooComplex("non-ASCII literal")
            byte_frag = nb.frag_byte_set({rune})
            frag = byte_frag if frag is None else nb.frag_concat(frag, byte_frag)
        return frag

    if op == kRegexpCharClass:
        byte_set = _charclass_byte_set(re.cc())
        if not byte_set:
            raise _TooComplex("empty or non-ASCII char class")
        return nb.frag_byte_set(byte_set)

    if op == kRegexpAnyByte:
        return nb.frag_byte_set(set(range(256)))

    if op == kRegexpAnyChar:
        # Byte-oriented "any byte except newline" — see module docstring.
        return nb.frag_byte_set(set(range(256)) - {0x0A})

    if op == kRegexpConcat:
        n = re.nsub()
        if n == 0:
            raise _TooComplex("empty concat")
        frag = None
        for i in range(n):
            child = re.sub()[i]
            child_op = child.op() if child != NULL else -1
            if child_op == kRegexpBeginText or child_op == kRegexpEndText:
                # Handled by the caller via outermost-anchor detection only —
                # any occurrence here (including nested-inside-concat) is
                # rejected by the caller's structural check before this
                # function is ever reached for the top-level node, but a
                # concat nested inside alternation/repeat could still surface
                # one here: refuse rather than silently drop the anchor.
                raise _TooComplex("nested anchor")
            child_frag = _build_fragment(nb, child)
            frag = child_frag if frag is None else nb.frag_concat(frag, child_frag)
        return frag

    if op == kRegexpAlternate:
        n = re.nsub()
        if n == 0:
            raise _TooComplex("empty alternate")
        frag = _build_fragment(nb, re.sub()[0])
        for i in range(1, n):
            frag = nb.frag_alt(frag, _build_fragment(nb, re.sub()[i]))
        return frag

    if op == kRegexpStar:
        if re.nsub() != 1:
            raise _TooComplex("malformed star")
        return nb.frag_star(_build_fragment(nb, re.sub()[0]))

    if op == kRegexpPlus:
        if re.nsub() != 1:
            raise _TooComplex("malformed plus")
        return nb.frag_plus(_build_fragment(nb, re.sub()[0]))

    if op == kRegexpQuest:
        if re.nsub() != 1:
            raise _TooComplex("malformed quest")
        return nb.frag_quest(_build_fragment(nb, re.sub()[0]))

    if op == kRegexpCapture:
        if re.nsub() != 1:
            raise _TooComplex("malformed capture")
        # RLIKE/LIKE-ANY are boolean match only — capture groups are
        # transparent (no \N replacement template involved here, unlike
        # REGEXP_REPLACE), so a capture group is just its inner pattern.
        return _build_fragment(nb, re.sub()[0])

    if op == kRegexpRepeat:
        if re.nsub() != 1:
            raise _TooComplex("malformed repeat")
        lo = re.min()
        hi = re.max()
        if lo < 0 or (hi != -1 and hi < lo):
            raise _TooComplex("malformed repeat bounds")
        total = lo + (hi - lo if hi != -1 else 0)
        if total > _REPEAT_UNROLL_CAP:
            raise _TooComplex("repeat bound too large")
        child = re.sub()[0]
        mandatory = None
        for i in range(lo):
            child_frag = _build_fragment(nb, child)
            mandatory = child_frag if mandatory is None else nb.frag_concat(mandatory, child_frag)
        if hi == -1:
            tail = nb.frag_star(_build_fragment(nb, child))
            return tail if mandatory is None else nb.frag_concat(mandatory, tail)
        optional_count = hi - lo
        if optional_count == 0:
            if mandatory is None:
                raise _TooComplex("empty repeat")
            return mandatory
        # Nest optionals so a later copy can't be taken without the earlier
        # ones: (c(c(c)?)?)? not (c)?(c)?(c)? (the latter would wrongly
        # accept e.g. skipping copy 1 but taking copy 2).
        nested = None
        for i in range(optional_count):
            copy_frag = _build_fragment(nb, child)
            step = copy_frag if nested is None else nb.frag_concat(copy_frag, nested)
            nested = nb.frag_quest(step)
        return nested if mandatory is None else nb.frag_concat(mandatory, nested)

    raise _TooComplex("unsupported node type %r" % (op,))


cdef object _epsilon_closure(list nfa_states, frozenset seed):
    stack = list(seed)
    closure = set(seed)
    while stack:
        s = stack.pop()
        for t in nfa_states[s].eps:
            if t not in closure:
                closure.add(t)
                stack.append(t)
    return frozenset(closure)


cpdef object compile_rlike_dfa(bytes pattern):
    """Compile a literal RLIKE/LIKE-ANY regex pattern into a DFA blob.

    Returns the serialized blob (bytes) on success, or None if the pattern
    is outside the supported scope (unsupported syntax, non-ASCII content,
    nested anchors, case-fold, or the resulting DFA exceeds the state cap).
    Callers MUST treat None as "fall through to a clean plan-time refusal",
    never as an error to surface directly.
    """
    cdef char* pattern_buf = NULL
    cdef Py_ssize_t pattern_len = 0
    cdef StringPiece pattern_piece
    cdef RegexpStatus status
    cdef Regexp* parsed = NULL
    cdef Regexp* simplified = NULL
    cdef Regexp* body = NULL
    cdef Regexp* first_child = NULL
    cdef Regexp* last_child = NULL
    cdef Regexp* child = NULL
    cdef bint has_begin = False
    cdef bint has_end = False
    cdef int n

    PyBytes_AsStringAndSize(pattern, &pattern_buf, &pattern_len)
    pattern_piece = StringPiece(pattern_buf, <size_t>pattern_len)
    parsed = Regexp.Parse(pattern_piece, LikePerl, &status)
    if parsed == NULL:
        return None

    try:
        simplified = parsed.Simplify()
        if simplified == NULL:
            return None

        if (simplified.parse_flags() & FoldCase) != 0:
            return None

        body = simplified
        skip_first = False
        skip_last = False
        if simplified.op() == kRegexpConcat and simplified.nsub() >= 1:
            n = simplified.nsub()
            first_child = simplified.sub()[0]
            last_child = simplified.sub()[n - 1]
            if first_child != NULL and first_child.op() == kRegexpBeginText:
                has_begin = True
                skip_first = True
            if last_child != NULL and last_child.op() == kRegexpEndText:
                has_end = True
                skip_last = True
        elif simplified.op() == kRegexpBeginText:
            has_begin = True
            has_end = False
            skip_first = True

        nb = _NfaBuilder()
        try:
            if simplified.op() == kRegexpConcat and (skip_first or skip_last):
                n = simplified.nsub()
                lo_idx = 1 if skip_first else 0
                hi_idx = n - 1 if skip_last else n
                if lo_idx >= hi_idx:
                    # Pattern was ONLY anchors, e.g. "^$" — matches empty string.
                    empty_state = nb.new_state()
                    start, accepts = empty_state, {empty_state}
                else:
                    frag = None
                    for i in range(lo_idx, hi_idx):
                        child = simplified.sub()[i]
                        if child.op() == kRegexpBeginText or child.op() == kRegexpEndText:
                            return None  # nested anchor beyond outermost
                        child_frag = _build_fragment(nb, child)
                        frag = child_frag if frag is None else nb.frag_concat(frag, child_frag)
                    start, accepts = frag
            else:
                start, accepts = _build_fragment(nb, simplified)
        except _TooComplex:
            return None

        # Unanchored search: rather than patching the DFA after the fact
        # (which only handles a failed match at the very first byte), add
        # the "search anywhere" behaviour to the NFA itself, before subset
        # construction. A fresh state with a self-loop on every byte plus an
        # epsilon into the real pattern start is always "active" — it's
        # present in the closure of every DFA state, because its own
        # self-loop keeps re-adding it to whatever byte was just consumed.
        # That lets a match starting mid-string be found even after an
        # earlier partial match at an earlier position has already failed,
        # which a start-state-only DFA patch cannot do (once you've
        # committed past the start state into a partial match, hitting a
        # dead transition there has no way back to "retry from here").
        if not has_begin:
            search_start = nb.new_state()
            nb.states[search_start].eps.add(start)
            for b in range(256):
                nb.states[search_start].trans[b] = search_start
            start = search_start

        # --- subset construction ---
        nfa_states = nb.states
        start_closure = _epsilon_closure(nfa_states, frozenset({start}))
        dfa_index = {start_closure: 0}
        dfa_order = [start_closure]
        dfa_accept = [bool(start_closure & accepts)]
        dfa_trans = [None]  # filled below, dfa_trans[i] = list[256] of state idx or None

        worklist = [0]
        while worklist:
            idx = worklist.pop()
            nfa_set = dfa_order[idx]
            row = [None] * 256
            for b in range(256):
                target_nfa = set()
                for s in nfa_set:
                    t = nfa_states[s].trans.get(b)
                    if t is not None:
                        target_nfa.add(t)
                if not target_nfa:
                    continue
                closure = _epsilon_closure(nfa_states, frozenset(target_nfa))
                existing = dfa_index.get(closure)
                if existing is None:
                    if len(dfa_order) >= DFA_STATE_CAP:
                        return None
                    existing = len(dfa_order)
                    dfa_index[closure] = existing
                    dfa_order.append(closure)
                    dfa_accept.append(bool(closure & accepts))
                    dfa_trans.append(None)
                    worklist.append(existing)
                row[b] = existing
            dfa_trans[idx] = row

        num_states = len(dfa_order)

        # --- serialize ---
        flags = 0
        if has_begin:
            flags |= 0x01
        if has_end:
            flags |= 0x02

        accept_bitmap = bytearray((num_states + 7) // 8)
        for i in range(num_states):
            if dfa_accept[i]:
                accept_bitmap[i >> 3] |= (1 << (i & 7))

        out = bytearray()
        out.append(1)
        out.append(flags)
        out += num_states.to_bytes(2, "little")
        out += bytes(accept_bitmap)
        for i in range(num_states):
            row = dfa_trans[i]
            for b in range(256):
                target = row[b]
                out += (0xFFFF if target is None else target).to_bytes(2, "little")

        return bytes(out)
    finally:
        if simplified != NULL:
            simplified.Decref()
        parsed.Decref()
