# THIS FILE IS AUTOMATICALLY UPDATED DURING THE BUILD PROCESS
# DO NOT EDIT THIS FILE DIRECTLY

__build__ = 217
__author__ = "@joocer"
__version__ = "0.6.5"
__lib__ = "opteryx-core"
__build_date__ = "2026-01-29T20:06:09.829200+00:00Z"

# Store the version here so:
# 1) we don't load dependencies by storing it in __init__.py
# 2) we can import it in setup.py for the same reason
# 3) we can import it in the CLI for the same reason
