#
# These checks run on every commit
#

name: Check on Every Push
on:
  push:
    branches-ignore:
      - main

jobs:

  secrets-scanning:
    uses: ./.github/workflows/secrets_scanning.yaml

  code-form:
    uses: ./.github/workflows/code_form.yaml

  native-fuzz-replay:
    uses: ./.github/workflows/fuzz_native_replay.yaml
